### ISSUE TITLE
No WiFi signal was found

### ISSUE THREAD

**Issue by 3dle** [Qrome/marquee-scroller#103]

**Comment by Qrome** [comment]
Can you give some more details?

**Comment by magnum129** [comment]
Are you not seeing any wifi networks? Do you have 2.4ghz Wireless G enabled on your router?

Under files, examples, examples for wemos d1, click the esp8266wifi, then the wifiscan example. Update the options, and try running that. Do you see any networks?

**Comment by 3dle** [comment]
I uploaded successfully according to your method. I restarted the mini board and did not see the WIFI name issued by the motherboard.

**Comment by magnum129** [comment]
Either you've got a defective wemos, or your WiFi isn't compatible with it.
Make sure your wireless router supports wireless G, and that it's enabled,
and that it's advertising is SSID.

**Comment by Qrome** [comment]
Make sure you compile it with 1M SPIFFS as well.

**Comment by 3dle** [comment]
It's 1M SPIFFS. Now it's OK. Thank you for your technical support.

**Comment by Qrome** [comment]
Cool, glad it is all working.
