### ISSUE TITLE
Should show CORRECT Time all the day...

### ISSUE THREAD

**Issue by Neeraj-Ch** [Qrome/marquee-scroller#104]
Hi Qrome. In past firmware versions, the clock shows correct time, if It gets connectivity once a day. 
But in version 2.10 Time resets to 12:00, if Clock founds no connection.

Please make some enhancement so that it should at least show correct time throughout the day, without any connection.

**Comment by magnum129** [comment]
Should be pretty simple to implement. Now that the time library in 2.11 has error reporting functionality. You could not update the time check to not sync if it falls pretty simply. You should give it a try, Neeraj-Ch.

**Comment by Neeraj-Ch** [comment]
Actually i am not so proficient in Programming. Could you tell me in which line number, i should have a try .🙄

**Comment by magnum129** [comment]
Take a look #106 @Neeraj-Ch 
Hopefully it'll work :-)

**Comment by Neeraj-Ch** [comment]
Thanks for help. 
Can we also do the same with Day & Date ?

**Comment by magnum129** [comment]
They are both fed from the same source

**Comment by Neeraj-Ch** [comment]
Please make changes to code if possible. 
Thanks

**Comment by magnum129** [comment]
Have you pulled and built the 2.11 version? It should already be in that
version. Try it and let me know.

**Comment by Neeraj-Ch** [comment]
Ya it is working fine. But for Time only.
No Date & Day scrolls.
I am requesting for Date & Day also.

**Comment by Qrome** [comment]
@Neeraj-Ch -- the intent of the Scrolling Clock was never to fully run offline.   It is expected to have an internet connection.   The recent changes were to get away from the GeoNames service and to an automated DST and time service.   Sorry, you may not get an OFF-Line working clock.

**Comment by Neeraj-Ch** [comment]
Then its ok. But if there is a chance, please try for a offline clock. For which data connection for only 1 time a day needed. And in absence of data it should show correct time, Date & day. With scroll.
Rest News & Octoprint service uses data

**Comment by magnum129** [comment]
Hi @Neeraj-Ch That sounds like a great idea for your first coding project! Good luck!

**Comment by Neeraj-Ch** [comment]
Hahaha. Thanks for all your support
I will try my best
