### ISSUE TITLE
Getting good weather data back, day/time is wrong

### ISSUE THREAD

**Issue by cheeto4493** [Qrome/marquee-scroller#107]
Getting valid weather data back and correct city, but time is UTC and day of month is 0

**Comment by Qrome** [comment]
What version are you using and did you add the new TimeZoneDB API key that is used starting in 7.10?

```TimeZoneDB free registration for API key: https://timezonedb.com/register -- this is used for setting the time and getting the correct time zone as well as managing time changes due to Day Light Savings time by regions. This key is set and managed only through the web interface and added in version 2.10 of Marquee Scroller. TimeZoneDB key is required for correct time display.```

**Comment by koendel** [comment]
Yes I’m having this problem too. Sometimes it does work but most of the time not. I have the timezonesdb api key configured. I have set it to refresh every 30 minutes. Most of the time it stops showing the correct time after a while. The weather stays correct all the time. Using 2.10

**Comment by Qrome** [comment]
Not sure it is the same problem, but your problem sounds like connectivity.    In previous releases if the time sync could not happen (network down) then it would just keep the previous time.   2.10 -- this changed.   The new release 2.11 should retain the previous time if connection fails.   You can go and try the 2.11 release now if you like.
