### ISSUE TITLE
Weather Data Error Unathorized

### ISSUE THREAD

**Issue by acestu** [Qrome/marquee-scroller#116]
Hi,
After putting my API and city id in settings for openweather.org I get a Weather Data Error saying that it is Unathorized, have they changed API's for Free accounts ?

thanks
Stuart

**Comment by Qrome** [comment]
You can test your API key directly with them.   Mine is currently working and I am not aware of any changes.

**Comment by acestu** [comment]
Hi Qrome, I have tested my openweathermap API in Postman using the same City ID, it returns the neccesary information and works fine, I created a new API and pasted it into the Marquee sketch togethor with the same city ID however I still get Weather Data Error 401 Unauthorised on the matrix, just to be certain this is the line from the sketch for city id:       
int CityIDs[] = { 2643266 }; //Only USE ONE for weather marquee

Thanks
Stuart

**Comment by Qrome** [comment]
@acestu -- If you are updating the Settings.h file then reloading it -- this will not update the settings.   It is noted in the Rreadme file.   Have you tried updating the API Key and City ID using the Web Interface?

**Comment by acestu** [comment]
Hi Qrome, allthough the matrix gives an ip address, if I try to connect on computer or phone, I see a quick blink on the board led but it will not connect, I did think that the board maybee faulty so I uploaded the MDParola example of esp8266 scrolling message which worked perfectly with the webserver page for setting the message etc. I then reuploaded the Marquee sketch and it is the same
Thanks
Stuart

**Comment by acestu** [comment]
Hi Qrome, I have just checked how to return the D1 to factory settings and it is quite long winded so I will order some new boards and try again.

Thanks
Stuart

**Comment by Qrome** [comment]
Make sure you have the ESP8266 Core 2.5.0 (not 2.5.1)  -- also make sure you specify 1M SPIFFS -- the application uses SPIFFS.

**Comment by acestu** [comment]
Ok Thanks for the info, it's a shame it dosen't work with the D1 mini Pro , I have lots of them lying around

Thanks Again
Stuart

**Comment by Qrome** [comment]
It does work with the D1 mini pro -- I use them.  Can you send me a link to the board you are using?

**Comment by acestu** [comment]
Hi Qrome, I don't have a link because I have had lots of these boards for years and I can't remember where I got them from, if I use a mini pro what settings should I use ?


Thanks
Stuart

**Comment by Qrome** [comment]
Make sure you have the:
- ESP8266 Core 2.5.0 installed
- Select the board "LOLIN(WEMOS) D1 R2 & mini" board
- Select Flash Size "4M (1M SPIFFS)"

If that compiles and loads, then I would suspect it will run.   Try pulling up the web interface.   Again -- important to have the ESP8266 Core at 2.5.0.

**Comment by acestu** [comment]
Hi Qrome, I tried flashing a D1 mini pro tonight I left spiffs on 14M spiffs, now the SSID for the device appears about 5 mins later, I set my WIFI in the webpage that comes up, however after that the Matrix scrolls with the IP address but when I try to go to the page on computer laptop or phone it just says waiting for page, I know you said make sure you have core 2.5.0. but how ddo I know or how can I find out what core it has ?

Thanks
Stuart

**Comment by Qrome** [comment]
Open Arduino --> Tools --> Boards --> Boards Manager...  
Then Filter on ESP8266 -- you should see what you have installed there and set it to 2.5.0.

**Comment by acestu** [comment]
Hi Qrome, Sucsess, I thought the core was the board firmware not the software that is used to program them, everything seems to work now apart from the news but that's another story, thanks so much for your help and percivering with me, I will close the thread now

thanks
Stuart

**Comment by Qrome** [comment]
Just an update on this, I spent some time with the code to make it compatible with the latest version of ESP8266 Core 2.5.2  -- you can now get the latest Marquee Scroller 2.14
