### ISSUE TITLE
OctoPrint Connection

### ISSUE THREAD

**Issue by DirtMonger** [Qrome/marquee-scroller#117]
Hi, I tried adding a connection for Octoprint, and it only seems to work once in a blue moon. I'll see the status once in a while, hours apart, so I know I have the OctoPrint configuration correct, but most of the time the Octoprint status in the UI is "Not Connected". Is there a likely culprit here that might be making my connection flakey? I've tried this on two different Octoprint instances (2 diff RasPi's), with the same results, so not sure what I have wrong. I'm on version 2.13 of the code.  I tried the serial monitor, but it was gibberish, figured I had the wrong speed, but haven't gone back yet to figure that out.  

Thanks!

**Comment by Qrome** [comment]
Are you using the IP address or a network name?   Try using the IP address.
When using the Serial Monitor, set speed to 115200.

**Comment by DirtMonger** [comment]
I'm currently using IP as I had no luck with hostname.  I'll give the serial monitor another shot as soon as I can sneak the thing away from my wife.  She saw it and claimed it as hers, lol.

**Comment by DirtMonger** [comment]
This is no longer an issue.  I installed a new router to get a better signal around the fringes of our house.  Didn't think the Marquee or Octopi was having any connection issue, but as soon as the new router was up, the problem was gone. Thanks for your help.

**Comment by Qrome** [comment]
Thanks for the update.
