### ISSUE TITLE
News hit and miss

### ISSUE THREAD

**Issue by acestu** [Qrome/marquee-scroller#120]
Hi Qrome,

When I first got the Marquee working I pasted my news API into the box but the news did not turn up on the Matrix only the source title ie google-news-uk , I noticed on the Marquee web page that it was still asking me to configure News even though my news api was already pased into the box, after unplugging the marquee the next time I plugged it in  the News was working on the marquee and it was no longer asking me to configure it on the web page, however after unplugging and plugging in again the News has gone again and I am being asked to configure it but with my api already in the box if i press save it returns to the homepage and is still asking me to configure news

thanks
Stuart

**Comment by acestu** [comment]
Hi Qrome,

I have noticed that if you choose a different source then sometimes it starts working, could news.api be at fault with sperodical uptime ?

thanks
Stuart

**Comment by Qrome** [comment]
Not all languages are supported -- due to the characters not supported by the fonts.

**Comment by Qrome** [comment]
Make sure you are running the latest code of Marquee Scroller -- you can also view the Serial Monitor in Arduino IDE over your COM port and baud rate of 115200 -- you will be able to see the details of the news api call and stuff like that.

**Comment by acestu** [comment]
Hi Qrome,
The sources I choose are English as one minute they are working and the next they are not, could this be a news.api issue ?

thanks
Stuart

**Comment by Qrome** [comment]
I have not seen that issue.  If you can view the details using the Arduino Serial monitor -- it would be able to provide you more information.

**Comment by acestu** [comment]
Hi Qrome,
I have just updated from 213 to 214  Now the wind speed is reported on marquee as 210  and on the web page it says:   kph WIND

The News does the same thing and in the serial monitor it says:

connection for news data failed: http://newsapi.org/v2/top-headlines?sources=hacker-news&apiKey=a58b7f4618544a7693300f44********

So I don't know if this means anything to you ?

Thanks
Stuart
![console](https://user-images.githubusercontent.com/4260227/58763695-42729d00-8556-11e9-80af-440a976dc8c0.png)

**Comment by Qrome** [comment]
The 210 degrees is the direction of the wind followed by the speed.   Wind direction is new.   The error you are seeing is connectivity.   Looks like connectivity issue.

**Comment by acestu** [comment]
Hi Qrome,

Yes wind makes sense now you have said direction,  It has just called for news again in monitor window same thing failed allthough I am blatently connected to the internet and watching TVplayer, I am using Nord VPN could this be anything to do with it  or maybe anti virus software, seems funny that it is intermittent.

thanks
Stuart

**Comment by Qrome** [comment]
What version of the ESP8266 Core did you compile with?   Make sure you are using 2.5.0 or later -- the binary in the download was compiled with ESP8266 Core 2.5.2 -- see if that helps.   

Your internet access is not the question -- it is the device connection stability.  What is the signal strength?   You say it works now and then -- so that is odd.   You are the only one reporting an issue on this.

**Comment by acestu** [comment]
H Qrome,
I have just been experimenting with connections and vpn, when connected with vpn my internet icon on the taskbar (win10) has a yellow exclamation mark and says unidentified network No internet access which i think is my vpn connection , browser and other connected items work, however if I dissconnect the vpn the icon now says that i have internet so if I unplug then plug the marquee back in then the news appears, I will try with core 2.5.2 now like you say

Thanks
Stuart

**Comment by Qrome** [comment]
The Marquee Scroller should have it's own IP from your router with public internet access through your gateway -- not sure why your Windows 10 VPN would have any affect on the clocks internet access.   I have no idea how you are configuring your network, but I have a feeling it is something on that end.

**Comment by acestu** [comment]
Hi Qrome,
Just updated everything, new board and it seems to be behaving itself, great work, thank you
Stuart

**Comment by Qrome** [comment]
That is good news.   Thanks for the update.
