### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by Ruko2010** [Qrome/marquee-scroller#121]
Hi, I'm really really new to Arduino Projects, so please be patient with me 😃.
I installed a fresh copy of Arduino IDE and then added all the necessary libs. But while compiling I get the following error. I hope somebody can help me.
`***/Library/Arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-3-20ed2b9/bin/xtensa-lx106-elf-g++ -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ -I***/Library/Arduino15/packages/esp8266/hardware/esp8266/2.5.2/tools/sdk/include -I***/Library/Arduino15/packages/esp8266/hardware/esp8266/2.5.2/tools/sdk/lwip2/include -I***/Library/Arduino15/packages/esp8266/hardware/esp8266/2.5.2/tools/sdk/libc/xtensa-lx106-elf/include -I/var/folders/t9/n_tk9d6s19gcs6wctr94_8tw0000gn/T/arduino_build_785220/core -c -w -Os -g -mlongcalls -mtext-section-literals -fno-rtti -falign-functions=4 -std=c++11 -MMD -ffunction-sections -fdata-sections -fno-exceptions -DNONOSDK221=1 -DF_CPU=80000000L -DLWIP_OPEN_SRC -DTCP_MSS=536 -DLWIP_FEATURES=1 -DLWIP_IPV6=0 -DARDUINO=10809 -DARDUINO_ESP8266_WEMOS_D1MINI -DARDUINO_ARCH_ESP8266 "-DARDUINO_BOARD=\"ESP8266_WEMOS_D1MINI\"" -DFLASHMODE_DIO -DESP8266 -I***/Library/Arduino15/packages/esp8266/hardware/esp8266/2.5.2/cores/esp8266 -I***/Library/Arduino15/packages/esp8266/hardware/esp8266/2.5.2/variants/d1_mini -I/Applications/Arduino.app/Contents/Java/libraries/WiFi/src -I***/Library/Arduino15/packages/esp8266/hardware/esp8266/2.5.2/libraries/ESP8266WiFi/src -I***/Library/Arduino15/packages/esp8266/hardware/esp8266/2.5.2/libraries/ESP8266WebServer/src -I***/Library/Arduino15/packages/esp8266/hardware/esp8266/2.5.2/libraries/ESP8266HTTPUpdateServer/src -I***/Documents/Arduino/libraries/WiFiManager-master -I***/Library/Arduino15/packages/esp8266/hardware/esp8266/2.5.2/libraries/DNSServer/src -I***/Library/Arduino15/packages/esp8266/hardware/esp8266/2.5.2/libraries/ESP8266mDNS/src -I***/Library/Arduino15/packages/esp8266/hardware/esp8266/2.5.2/libraries/ArduinoOTA -I***/Library/Arduino15/packages/esp8266/hardware/esp8266/2.5.2/libraries/SPI -I***/Documents/Arduino/libraries/Adafruit-GFX-Library-master -I***/Documents/Arduino/libraries/arduino-Max72xxPanel-master -I***/Documents/Arduino/libraries/Time-master -I***/Library/Arduino15/packages/esp8266/hardware/esp8266/2.5.2/libraries/ESP8266HTTPClient/src -I***/Documents/Arduino/libraries/json-streaming-parser-master /var/folders/t9/n_tk9d6s19gcs6wctr94_8tw0000gn/T/arduino_build_785220/sketch/PiHoleClient.cpp -o /var/folders/t9/n_tk9d6s19gcs6wctr94_8tw0000gn/T/arduino_build_785220/sketch/PiHoleClient.cpp.o
In file included from /var/folders/t9/n_tk9d6s19gcs6wctr94_8tw0000gn/T/arduino_build_785220/sketch/Settings.h:44:0,
                 from ***/Downloads/marquee-scroller-master/marquee/marquee.ino:28:
***/Library/Arduino15/packages/esp8266/hardware/esp8266/2.5.2/libraries/ESP8266WebServer/src/ESP8266WebServer.h: In member function 'virtual size_t ESP8266WebServer::_currentClientWrite_P(const char*, size_t)':
***/Library/Arduino15/packages/esp8266/hardware/esp8266/2.5.2/libraries/ESP8266WebServer/src/ESP8266WebServer.h:142:83: error: 'class WiFiClient' has no member named 'write_P'
   virtual size_t _currentClientWrite_P(PGM_P b, size_t l) { return _currentClient.write_P( b, l ); }
                                                                                   ^
In file included from ***/Library/Arduino15/packages/esp8266/hardware/esp8266/2.5.2/libraries/ESP8266mDNS/src/ESP8266mDNS.h:45:0,
                 from /var/folders/t9/n_tk9d6s19gcs6wctr94_8tw0000gn/T/arduino_build_785220/sketch/Settings.h:47,
                 from ***/Downloads/marquee-scroller-master/marquee/marquee.ino:28:
***/Library/Arduino15/packages/esp8266/hardware/esp8266/2.5.2/libraries/ESP8266mDNS/src/ESP8266mDNS_Legacy.h: At global scope:
***/Library/Arduino15/packages/esp8266/hardware/esp8266/2.5.2/libraries/ESP8266mDNS/src/ESP8266mDNS_Legacy.h:131:3: error: 'WiFiEventHandler' does not name a type
   WiFiEventHandler _disconnectedHandler;
   ^
***/Library/Arduino15/packages/esp8266/hardware/esp8266/2.5.2/libraries/ESP8266mDNS/src/ESP8266mDNS_Legacy.h:132:3: error: 'WiFiEventHandler' does not name a type
   WiFiEventHandler _gotIPHandler;
   ^
In file included from ***/Library/Arduino15/packages/esp8266/hardware/esp8266/2.5.2/libraries/ESP8266mDNS/src/ESP8266mDNS.h:46:0,
                 from /var/folders/t9/n_tk9d6s19gcs6wctr94_8tw0000gn/T/arduino_build_785220/sketch/Settings.h:47,
                 from ***/Downloads/marquee-scroller-master/marquee/marquee.ino:28:
***/Library/Arduino15/packages/esp8266/hardware/esp8266/2.5.2/libraries/ESP8266mDNS/src/LEAmDNS.h:1153:5: error: 'WiFiEventHandler' does not name a type
     WiFiEventHandler                m_DisconnectedHandler;

     ^
***/Library/Arduino15/packages/esp8266/hardware/esp8266/2.5.2/libraries/ESP8266mDNS/src/LEAmDNS.h:1154:5: error: 'WiFiEventHandler' does not name a type
     WiFiEventHandler                m_GotIPHandler;

     ^
***/Downloads/marquee-scroller-master/marquee/marquee.ino: In function 'void setup()':
marquee:272:25: error: no matching function for call to 'WiFiClass::disconnect(bool)'
     WiFi.disconnect(true);
                         ^
***/Downloads/marquee-scroller-master/marquee/marquee.ino:272:25: note: candidate is:
In file included from /var/folders/t9/n_tk9d6s19gcs6wctr94_8tw0000gn/T/arduino_build_785220/sketch/Settings.h:1:0,
                 from ***/Downloads/marquee-scroller-master/marquee/marquee.ino:28:
/Applications/Arduino.app/Contents/Java/libraries/WiFi/src/WiFi.h:130:9: note: int WiFiClass::disconnect()
     int disconnect(void);
         ^
/Applications/Arduino.app/Contents/Java/libraries/WiFi/src/WiFi.h:130:9: note:   candidate expects 0 arguments, 1 provided
***/Downloads/marquee-scroller-master/marquee/marquee.ino: In function 'void configModeCallback(WiFiManager*)':
marquee:1194:23: error: 'class WiFiClass' has no member named 'softAPIP'
   Serial.println(WiFi.softAPIP());
                       ^
Bibliothek WiFi in Version 1.2.7 im Ordner: /Applications/Arduino.app/Contents/Java/libraries/WiFi  wird verwendet
Bibliothek ESP8266WiFi in Version 1.0 im Ordner: ***/Library/Arduino15/packages/esp8266/hardware/esp8266/2.5.2/libraries/ESP8266WiFi  wird verwendet
Bibliothek ESP8266WebServer in Version 1.0 im Ordner: ***/Library/Arduino15/packages/esp8266/hardware/esp8266/2.5.2/libraries/ESP8266WebServer  wird verwendet
Bibliothek ESP8266HTTPUpdateServer in Version 1.0 im Ordner: ***/Library/Arduino15/packages/esp8266/hardware/esp8266/2.5.2/libraries/ESP8266HTTPUpdateServer  wird verwendet
Bibliothek WiFiManager-master in Version 0.14 im Ordner: ***/Documents/Arduino/libraries/WiFiManager-master  wird verwendet
Bibliothek DNSServer in Version 1.1.1 im Ordner: ***/Library/Arduino15/packages/esp8266/hardware/esp8266/2.5.2/libraries/DNSServer  wird verwendet
Bibliothek ESP8266mDNS in Version 1.2 im Ordner: ***/Library/Arduino15/packages/esp8266/hardware/esp8266/2.5.2/libraries/ESP8266mDNS  wird verwendet
Bibliothek ArduinoOTA in Version 1.0 im Ordner: ***/Library/Arduino15/packages/esp8266/hardware/esp8266/2.5.2/libraries/ArduinoOTA  wird verwendet
Bibliothek SPI in Version 1.0 im Ordner: ***/Library/Arduino15/packages/esp8266/hardware/esp8266/2.5.2/libraries/SPI  wird verwendet
Bibliothek Adafruit-GFX-Library-master in Version 1.5.6 im Ordner: ***/Documents/Arduino/libraries/Adafruit-GFX-Library-master  wird verwendet
Bibliothek arduino-Max72xxPanel-master im Ordner: ***/Documents/Arduino/libraries/arduino-Max72xxPanel-master (legacy) wird verwendet
Bibliothek Time-master in Version 1.5 im Ordner: ***/Documents/Arduino/libraries/Time-master  wird verwendet
Bibliothek ESP8266HTTPClient in Version 1.2 im Ordner: ***/Library/Arduino15/packages/esp8266/hardware/esp8266/2.5.2/libraries/ESP8266HTTPClient  wird verwendet
Bibliothek json-streaming-parser-master in Version 1.0.5 im Ordner: ***/Documents/Arduino/libraries/json-streaming-parser-master  wird verwendet
exit status 1
no matching function for call to 'WiFiClass::disconnect(bool)'
`

If it is necessary, I use Arduino on Mac. Here is a screenshot of my included Libs:
<img width="230" alt="grafik" src="https://user-images.githubusercontent.com/2239440/61904245-bca41a00-af26-11e9-8f63-6b0789d862f2.png">

Thanks in advance.

**Comment by Qrome** [comment]
I also have it setup and compiling on a Mac -- setup and installation of board and library files are the same.

1.   Make sure you have loaded the latest Arduino IDE
2.  Follow the readme.md file to make sure you have loaded the ESP8266 Core (board library and ESP8266 core libraries).

Follow the compile section in detail:  https://github.com/Qrome/marquee-scroller#compiling-and-loading-to-wemos-d1

**Comment by Ruko2010** [comment]
1. I downloaded the latest arduino ide just before trying.
2. For this point. I added the ESP Board via the Board Manager, but how can I add the ESP8266 Core Libraries? When I search for "ESP8266 Core" in Library Manager I only see this one:
<img width="786" alt="grafik" src="https://user-images.githubusercontent.com/2239440/61907901-b87bfa80-af2e-11e9-8d55-ca7ef60588af.png">

**Comment by Qrome** [comment]
Use the Board Manager to load the ESP8266 Core.

Tools -> Board -> Board Manager...

![image](https://user-images.githubusercontent.com/32021227/61908187-04558200-aee4-11e9-80b2-f8ffbe7a5059.png)

**Comment by Qrome** [comment]
Also, make sure you have updated the Preferences as mentioned in the readme.md

![image](https://user-images.githubusercontent.com/32021227/61908309-3ff04c00-aee4-11e9-86b3-d07141661acd.png)

**Comment by Ruko2010** [comment]
Yes, i‘ve done that.

**Comment by Ruko2010** [comment]
I think there is a Library missing, but I installed all of the Libs from the Readme. And I'm not sure which one could be missing.

`no matching function for call to 'WiFiClass::disconnect(bool)'`

Just in Case: If I just click on "Verify" in Arduino, the ESP must not be connected to the Mac, right? I have to connect it, when I want to Flash the Software to the ESP.

**Comment by Ruko2010** [comment]
Do I have to "include" the added Libs somehow, or is it enough to just install them via the Lib-Manager?

**Comment by Ruko2010** [comment]
ok, don't hit me 😃. I found the issue.
I'm not sure why, but in my Setting.h were some extra includes:

#include <WiFi.h>
#include <WiFiUdp.h>
#include <WiFiClient.h>
#include <WiFiServer.h>


Maybe I accidentally added them while adding the Libs.
I removed them and now the compilation is working 😃. When I'm at home I will try to upload it to the ESP.
Nevertheless, thanks for the help!

**Comment by kd4pba** [comment]
Nice, Too bad we still have to pull our hair out trying to find an install wifi.h.  I can't use binaries due to my display being ultra wide.
