### ISSUE TITLE
Drive a LED ON/OFF via WebServer

### ISSUE THREAD

**Issue by Neeraj-Ch** [Qrome/marquee-scroller#122]
Hi Qrome, 

In last few days i have tried my best to integrate a small code to drive a PIN of ESP8266 ON/OFF via web server, but didn't suceeded. I Want to drive a relay/AC Load via the web server.
Actually i am not proficient in Coding.

So require some of your time & Skills.
Please if you can integrate a code to Drive a Relay.

Thanks

**Comment by Neeraj-Ch** [comment]
Anybody else, if can do help of me. Please

**Comment by Neeraj-Ch** [comment]
Anybody there ?

**Comment by fixyourlan** [comment]
Search google for help. There are many sites that show how to do this with example code. Search how to program esp8266 to control a relay.  This is not the place to be asking for help for this if it is not related to this project!

Jim Bazar

On Aug 18, 2019, at 9:21 PM, Neeraj-Ch <notifications@github.com> wrote:

Anybody there ?

**Comment by Neeraj-Ch** [comment]
Hi Zim, Actually i have many codes for this. The codes are simple. I had done a lot of googling. But integrating code is a Nightmare for me. That's why my all hope is to you all. I am helpless. 
By the way thanks for replying.

**Comment by Neeraj-Ch** [comment]
Hi Qrome & everyone here.

I tried everything to Drive an LED via an Option in Web Server/Interface of your Code. 

Actually i wanted to integrate an LED in Marquee-Scroller, which can be controlled by Web-Interface of it. But found No success. ☹️

I think an LED Light can be much useful during Night & the way controlling it might be Fun.

Problem for me is Altering the code. I have no problems for Electronics stuff.

It's been a long time trying to do so (~4 Months) You all are my last hope.

**Comment by Neeraj-Ch** [comment]
> Hi Qrome & everyone here.
> 
> I tried everything to Drive an LED via an Option in Web Server/Interface of your Code.
> 
> Actually i wanted to integrate an LED in Marquee-Scroller, which can be controlled by Web-Interface of it. But found No success. ☹️
> 
> I think an LED Light can be much useful during Night & the way controlling it might be Fun.
> 
> Problem for me is Altering the code. I have no problems for Electronics stuff.
> 
> It's been a long time trying to do so (~4 Months) You all are my last hope.


Anybody here interested to Help?
