### ISSUE TITLE
Unordered display on the led array

### ISSUE THREAD

**Issue by DensRever** [Qrome/marquee-scroller#124]
I just ordered a led matrix from bangood, but the display is messy.
After search the type of the matrix is ​​ICSTATION_HW.
Is this matrix compatible with this project?
Thanks for your help.

**Comment by Qrome** [comment]
Yes, it should be supported.   Some brands have the LED set in different rotations.   Try changing the ledRotation value in the Settings.h file -- this should correct it for you.

**Comment by fixyourlan** [comment]
Attach a picture of what you mean “messy”!

Jim Bazar

On Aug 28, 2019, at 3:09 PM, DensRever <notifications@github.com> wrote:

I just ordered a led matrix from bangood, but the display is messy.
After search the type of the matrix is ​​ICSTATION_HW.
Is this matrix compatible with this project?
Thanks for your help.

**Comment by Qrome** [comment]
The other thing to check is:

Set 1M SPIFFS -- this project requires SPIFFS for saving and reading configuration settings.

This is part of the readme file -- if you do not set this in the Arduino IDE then when it boots up... the LEDS may look like a mess.

**Comment by DensRever** [comment]
Hello and thank's for your help.
BEFORE
![before](https://user-images.githubusercontent.com/41828675/63971421-b1548900-caa6-11e9-81bd-661200cd6a9a.jpg)

In the setting.h i make changes like this : The changes are writed bold.

// Display Settings
// CLK -> D5 (SCK)  
// CS  -> D6 
// DIN -> D7 (MOSI)
const int pinCS = D6; // Attach CS to this pin, DIN to MOSI and CLK to SCK (cf http://arduino.cc/en/Reference/SPI )
int displayIntensity = 1;  //(This can be set from 0 - 15)
### **const int numberOfHorizontalDisplays = 8**; // default 4 for standard 4 x 1 display Max size of 16
const int numberOfVerticalDisplays = 1; // default 1 for a single row height
/* set ledRotation for LED Display panels (3 is default)
0: no rotation
1: 90 degrees clockwise
2: 180 degrees
3: 90 degrees counter clockwise (default)
*/
### **### int ledRotation = 1;**

const int numberOfHorizontalDisplays = 8 - for 2 modules of 4 matrix leds
ledRotation = 1 - for the matrix "led" who comes from Bangood.

Now all works correctly

As Qrome says, you must read the Readme file carefully for the IDE arduino to work properly. Thank you very much to the people who helped.
Cordially.
Denis.

**Comment by Qrome** [comment]
Glad you got it working.

**Comment by DensRever** [comment]
Where's my comments ?
