### ISSUE TITLE
Settings.h error compiling Delcaration.

### ISSUE THREAD

**Issue by kd4pba** [Qrome/marquee-scroller#130]
Forgive my ignorance but I seem to have issues compiling that trace back to settings.h 
In file included from D:\new\marquee-scroller-master\marquee\marquee.ino:28:0:

Settings.h:86:19: error: 'D6' was not declared in this scope

 const int pinCS = D6; // Attach CS to this pin, DIN to MOSI and CLK to SCK (cf http://arduino.cc/en/Reference/SPI )

If this is changed to 6 from D6 it compiles however additional errors related to pin not being declared appear.  Changing that from D2 to 2 allows me to compile however this appears to be non functional as I can not communicate with the 8266. 

Thinking I screwed this up I went back to the stock files and pulled them again.  I get the same errors so I am a little confused as to what is wrong.

**Comment by Qrome** [comment]
It sounds like you may not have the correct board selected in the Arduino IDE.  Select the one listed in the Readme.md file.
