### ISSUE TITLE
time update failing

### ISSUE THREAD

**Issue by roeschu75** [Qrome/marquee-scroller#133]
Hi,
I'm new to marquee-scroller and setting it up for the first time. So there is a possibility I'm doing something wrong.

It seems I can't get the time updated/set. It fails,but does not tell why it is unsuccessful

On the serial monitor I can see
...
Updating Time...
News Data for 
Getting Time Data for 51.84,4.97
GET /v2.1/get-time-zone?key="myAPIkey"&format=json&by=position&lat=51.84&lng=4.97 HTTP/1.1
Waiting for data

Time update unsuccessful!
 ...

-- "myAPYkey" = key removed for security reason, let me know if you need my key 
-- Weather data is updated fine
-- I double checked the timezonedb api key multiple times and also changed it to different locations with no change
-- what I can see on the timezonedb site is that they have also a username, together with the apikey, does that have to get included somehow ?

thanks for any help

Cheers
Roger

**Comment by Qrome** [comment]
When you get the key from timezonedb they send an email to you.  You then have to activate the key.  Do you know if this was done?

**Comment by roeschu75** [comment]
Yes, the account is activated.

**Comment by roeschu75** [comment]
closing issue as reason has been found.
thanks for the assistance.

the issue is not fixed, but not related to marquee-scroller.

a tcpdump on my firewall revealed

12:06:56.084703 IP laap1.serverrunners.com.http > myfirewallIP.57708: Flags [.], seq 640:2088, ack 688, win 63, options [nop,nop,TS val 1705284971 ecr 2333970439], length 1448: HTTP: HTTP/1.1 503 Service Temporarily Unavailable

Already got in touch with Sei Kan from timezonedb

Thanks and cheers

Roger

**Comment by shrmnk** [comment]
Encountered the same thing and mine was because my timezonedb account was not yet verified - just in case anyone else experiences this.
