### ISSUE TITLE
Turn display on/off through URL

### ISSUE THREAD

**Issue by TheLion** [Qrome/marquee-scroller#135]
Hi,

Is there a way to turn the display on/off through a URL? 

I noticed that http://<ip-address>/display toggles the display, but with this there is no 100% telling it is on or off, for example when a command was not issued/executed correctly. Is there an additional parameter to specify on or off?

**Comment by Qrome** [comment]
Yes, and it works.   I just tested it on my display here.   When you pull up the web interface, you will see a menu item that says "Turn Display Off" -- the URL is a toggle.   If the display is on, then it turns off.   If it is off then it will turn on.   Sample URL:  http://192.168.0.193/display

**Comment by TheLion** [comment]
Hi,

Yes, I found that out too, but I mean something like: http://192.168.0.193/display=on and http://192.168.0.193/display=off

Because when I call the URL from another system, I have to be sure it does what I want and doesn't toggle the opposite because a toggle was missed somewhere in the past.

**Comment by Qrome** [comment]
No, currently there is no other flag.  Not to say you couldn't add it easily.   It is simply a toggle.

**Comment by TheLion** [comment]
Thanks.

**Comment by Qrome** [comment]
Ok, this is all you need to add.   In the marquee.ino file at line 325:

`    server.on("/display/on", handleDisplayOn);
    server.on("/display/off", handleDisplayOff);`

Then further down near the other handleDisplay() method put the following two methods:

`void handleDisplayOn() {
  if (!athentication()) {
    return server.requestAuthentication();
  }

  enableDisplay(true);
  displayMessage("Display turned ON");
}

void handleDisplayOff() {
  if (!athentication()) {
    return server.requestAuthentication();
  }

  enableDisplay(false);
  displayMessage("Display turned OFF");
}`

I just tested this.   You would always send /display/on for on and /display/off for off.

**Comment by TheLion** [comment]
Thanks! Works like a charm.

Is this also possible for your PiHole and Octoprint monitors ;-)
