### ISSUE TITLE
Need help to use 1*8 led panel

### ISSUE THREAD

**Issue by stefaie** [Qrome/marquee-scroller#141]
Hello
I use a 1*8 led panel and it works but on two 4 panel in same time.
I ve read I must modified the settings.h to change it but I can't do it on windows 10.
access denied .   every time .
I tried to modify attributes of settings.h but no way.I don't know how write in this settings.h.
Thanks for help

**Comment by Qrome** [comment]
There is no trick to editing a plain text file.   Are you using the Arduino IDE?   Unless you have some other software protection that prevents you from editing files you download from the internet.

**Comment by stefaie** [comment]
Thanks very much,it's ok now ,like you tell me to do.Great job ,it will be perfect if we can choose language for date  and weather...
Very happy...just to do a cool box to put it in .
