### ISSUE TITLE
Receiving weather in own language

### ISSUE THREAD

**Issue by APteH** [Qrome/marquee-scroller#144]
Hello, my name is Arie and I live in The Netherlands. I am  **77** year now  and I started 2 years ago with C++. I don't have enough expirience to write my own programs but changing a little and small modification, I can . However after reading the info on Openweathermaps, it seems to  be that  it is possible to receive the forecast in  foreign languages. by adding example  "lan=nl" . And that I try for many times but I am not succeedded. Can please advise me where and how to do? 
I am very happy with your Marquee- scroller an thank you for that.
Hopefully I will receive a solutions. Sorry for typing errors as it is not my native language.
Arie 
prins.arie@gmail.com

**Comment by APteH** [comment]
Any one ??

**Comment by Qrome** [comment]
No, sorry, like you mentioned the Openweathermaps -- does not translate all the weather conditions to other languages.   As a result, this would have to happen in the local code of the device.   There is no plan at this time to add language files to the solution.   
You could always provide your own translation for all the conditions though.  But that would be your local unique version.

This has been mentioned before but I am sure the thread is long past.   Thanks and enjoy.
