### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by osb99** [Qrome/marquee-scroller#149]
Hi, I get this error code when compiling, please can someone help?

In file included from /Users/jamesosborne/Library/Arduino15/packages/esp8266/hardware/esp8266/2.7.4/tools/sdk/libc/xtensa-lx106-elf/include/sys/stdio.h:6:0,
                 from /Users/jamesosborne/Library/Arduino15/packages/esp8266/hardware/esp8266/2.7.4/tools/sdk/libc/xtensa-lx106-elf/include/stdio.h:63,
                 from /Users/jamesosborne/Library/Arduino15/packages/esp8266/hardware/esp8266/2.7.4/cores/esp8266/Arduino.h:32,
                 from sketch/marquee.ino.cpp:1:
/Users/jamesosborne/Library/Arduino15/packages/esp8266/hardware/esp8266/2.7.4/tools/sdk/libc/xtensa-lx106-elf/include/sys/pgmspace.h:25:130: error: 'const char HTTP_HEAD []' redeclared as different kind of symbol
   #define PROGMEM __attribute__((section( "\".irom.text." __FILE__ "." __STRINGIZE(__LINE__) "."  __STRINGIZE(__COUNTER__) "\"")))
                                                                                                                                  ^
/Users/jamesosborne/Documents/Arduino/libraries/WiFiManager/WiFiManager.h:25:24: note: in expansion of macro 'PROGMEM'
 const char HTTP_HEAD[] PROGMEM            = "<!DOCTYPE html><html lang=\"en\"><head><meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\"/><title>{v}</title>";
                        ^
In file included from sketch/Settings.h:39:0,
                 from /Users/jamesosborne/Downloads/marquee-scroller-master/marquee/marquee.ino:28:
/Users/jamesosborne/Library/Arduino15/packages/esp8266/hardware/esp8266/2.7.4/libraries/ESP8266WebServer/src/ESP8266WebServer.h:34:39: error: previous declaration of 'HTTPMethod HTTP_HEAD'
 enum HTTPMethod { HTTP_ANY, HTTP_GET, HTTP_HEAD, HTTP_POST, HTTP_PUT, HTTP_PATCH, HTTP_DELETE, HTTP_OPTIONS };
                                       ^
exit status 1
Error compiling for board LOLIN(WEMOS) D1 R2 & mini.

**Comment by Qrome** [comment]
You need to use ESP8266 core 2.5.2.

**Comment by osb99** [comment]
> You need to use ESP8266 core 2.5.2.

How do I do that?

**Comment by osb99** [comment]
> You need to use ESP8266 core 2.5.2.

Perfect, thank you!
