### ISSUE TITLE
Successfully compiled and uploaded, but no welcome message, displaying strangely

### ISSUE THREAD

**Issue by osb99** [Qrome/marquee-scroller#150]
![IMG_2865](https://user-images.githubusercontent.com/69733374/90321604-34365400-df43-11ea-84a5-3057dbf758e3.jpg)

**Comment by Qrome** [comment]
This is also mentioned in the readme.MD file. You need to turn on 1M spiffs.  This is so it can write the configuration file to the file system.

**Comment by osb99** [comment]
> This is also mentioned in the readme.MD file. You need to turn on 1M spiffs. This is so it can write the configuration file to the file system.

Thanks, it worked.
