### ISSUE TITLE
Marquee-Scroller Web page Password User Name recovery

### ISSUE THREAD

**Issue by LenK13** [Qrome/marquee-scroller#152]
To all concerned:
I realize this is not the normal method of making contact with you and the Team.  But I need some serious help. I just finished replicating the You Tube project posted for the Weather Marque Clock News Station ("ESP8266 Wemos Clock News Weather Scrolling Marquee | Arduino").  Reference:  "https://www.youtube.com/watch?v=_jpMv5YaToE". 

Outstanding Video.  This is the FIRST Time I have been able to get a ESP Module to work for me.  That and a previous related Video posted, allowed me to get the Max7219 working properly for the first time.  Good Stuff. The information is sound and does work.

Problem I have is after all the work hours of debugging and trying to understand "CODING", making corrections/adjustments, registering the weather sites, news sites and time site to receive API Keys, I am now locked out of the "Weather Marque Web page".  The USER Name and Password will not allow me back into the settings to make adjustments. How is it that I can reset this?  Or can you reset this for me?

I really would appreciate your support in resolving this issue "Recovery - User Name & Password".  Thank you in advance.

Respectfully, 

Leonard

**Comment by Qrome** [comment]
Leonard,

Have the unit pluged into your comuter, have the Serial Monitor open and using baud 115200.  Press the reset button on the Wemos D1 Mini -- when it boots up, it will display the settings including the user / password.

**Comment by LenK13** [comment]
Qrome,

Thank you so much for your quick response.!  I did as you recommended and Wa-La..!  Serial Monitor showed USER Name and Password, just as you stated.

Thank you..  Truly appreciate your support regarding this matter.

Respectfully,

Leonard

**Comment by LenK13** [comment]
Thank You for the information/solution.
Explanation was prompt, clear, concise and functional.

Respectfully,
Leonard
    On Wednesday, August 26, 2020, 12:51:01 PM PDT, Qrome <notifications@github.com> wrote:  
 
 


Leonard,

Have the unit pluged into your comuter, have the Serial Monitor open and using baud 115200. Press the reset button on the Wemos D1 Mini -- when it boots up, it will display the settings including the user / password.
