### ISSUE TITLE
Seconds

### ISSUE THREAD

**Issue by finnie2006** [Qrome/marquee-scroller#158]
Is it possible to show the time but also with the seconds so hour minute second

21:12:56

like that

**Comment by finnie2006** [comment]
And i have a nodemcu does that also work so if it does i dont need to buy i wemos

**Comment by Qrome** [comment]
If you make the double wide, it will show the option to show the seconds.   I know people have used the nodemcu -- the case is not designed for that board though.

**Comment by finnie2006** [comment]
oh its nice that it can show seconds with 2, then i also will buy the wemos because if it will not work on the nodemcu then its sas xd

thx for the fast support
