### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by finnie2006** [Qrome/marquee-scroller#159]

**Comment by finnie2006** [comment]
and i get this error

Arduino: 1.8.13 (Windows 10), Board: "LOLIN(WEMOS) D1 mini Lite, 80 MHz, Flash, Legacy (new can return nullptr), All SSL ciphers (most compatible), 1MB (FS:64KB OTA:~470KB), v2 Lower Memory, Disabled, None, Only Sketch, 921600"


In file included from sketch\TimeDB.h:2:0,

                 from sketch\Settings.h:50,

                 from C:\Users\Finnt\Desktop\marquee-scroller-master\marquee\marquee.ino:33:

C:\Users\Finnt\Documents\Arduino\libraries\Adafruit-GFX-Library-master/Adafruit_GrayOLED.h:30:32: fatal error: Adafruit_I2CDevice.h: No such file or directory

 #include <Adafruit_I2CDevice.h>

                                ^

compilation terminated.

exit status 1

Error compiling for board LOLIN(WEMOS) D1 mini Lite.



This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by finnie2006** [comment]
Arduino: 1.8.13 (Windows 10), Board: "LOLIN(WEMOS) D1 mini Lite, 80 MHz, Flash, Legacy (new can return nullptr), All SSL ciphers (most compatible), 1MB (FS:64KB OTA:~470KB), v2 Lower Memory, Disabled, None, Only Sketch, 921600"





















In file included from C:\Users\Finnt\Desktop\marquee-scroller-master\marquee\marquee.ino:19:0:

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:46:1: error: 'ESP8266WebServerTemplate' does not name a type

 ESP8266WebServerTemplate<ServerType>::ESP8266WebServerTemplate(IPAddress addr, int port)

 ^

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:68:1: error: 'ESP8266WebServerTemplate' does not name a type

 ESP8266WebServerTemplate<ServerType>::ESP8266WebServerTemplate(int port)

 ^

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:90:1: error: 'ESP8266WebServerTemplate' does not name a type

 ESP8266WebServerTemplate<ServerType>::~ESP8266WebServerTemplate() {

 ^

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:103:30: error: expected initializer before '<' token

 void ESP8266WebServerTemplate<ServerType>::enableCORS(bool enable) {

                              ^

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:107:30: error: expected initializer before '<' token

 void ESP8266WebServerTemplate<ServerType>::begin() {

                              ^

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:113:30: error: expected initializer before '<' token

 void ESP8266WebServerTemplate<ServerType>::begin(uint16_t port) {

                              ^

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:119:32: error: expected initializer before '<' token

 String ESP8266WebServerTemplate<ServerType>::_extractParam(String& authReq,const String& param,const char delimit) const {

                                ^

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:127:30: error: expected initializer before '<' token

 bool ESP8266WebServerTemplate<ServerType>::authenticate(const char * username, const char * password){

                              ^

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:165:30: error: expected initializer before '<' token

 bool ESP8266WebServerTemplate<ServerType>::authenticateDigest(const String& username, const String& H1)

                              ^

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:243:32: error: expected initializer before '<' token

 String ESP8266WebServerTemplate<ServerType>::_getRandomHexString() {

                                ^

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:253:30: error: expected initializer before '<' token

 void ESP8266WebServerTemplate<ServerType>::requestAuthentication(HTTPAuthMethod mode, const char* realm, const String& authFailMsg) {

                              ^

In file included from C:\Users\Finnt\Desktop\marquee-scroller-master\marquee\marquee.ino:19:0:

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:271:30: error: expected initializer before '<' token

 void ESP8266WebServerTemplate<ServerType>::on(const Uri &uri, ESP8266WebServerTemplate<ServerType>::THandlerFunction handler) {

                              ^

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:276:30: error: expected initializer before '<' token

 void ESP8266WebServerTemplate<ServerType>::on(const Uri &uri, HTTPMethod method, ESP8266WebServerTemplate<ServerType>::THandlerFunction fn) {

                              ^

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:281:30: error: expected initializer before '<' token

 void ESP8266WebServerTemplate<ServerType>::on(const Uri &uri, HTTPMethod method, ESP8266WebServerTemplate<ServerType>::THandlerFunction fn, ESP8266WebServerTemplate<ServerType>::THandlerFunction ufn) {

                              ^

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:286:30: error: expected initializer before '<' token

 void ESP8266WebServerTemplate<ServerType>::addHandler(RequestHandlerType* handler) {

                              ^

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:291:30: error: expected initializer before '<' token

 void ESP8266WebServerTemplate<ServerType>::_addRequestHandler(RequestHandlerType* handler) {

                              ^

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:303:30: error: expected initializer before '<' token

 void ESP8266WebServerTemplate<ServerType>::serveStatic(const char* uri, FS& fs, const char* path, const char* cache_header) {

                              ^

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:308:30: error: expected initializer before '<' token

 void ESP8266WebServerTemplate<ServerType>::handleClient() {

                              ^

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:374:30: error: expected initializer before '<' token

 void ESP8266WebServerTemplate<ServerType>::close() {

                              ^

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:382:30: error: expected initializer before '<' token

 void ESP8266WebServerTemplate<ServerType>::stop() {

                              ^

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:387:30: error: expected initializer before '<' token

 void ESP8266WebServerTemplate<ServerType>::sendHeader(const String& name, const String& value, bool first) {

                              ^

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:402:30: error: expected initializer before '<' token

 void ESP8266WebServerTemplate<ServerType>::setContentLength(const size_t contentLength) {

                              ^

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:407:30: error: expected initializer before '<' token

 void ESP8266WebServerTemplate<ServerType>::_prepareHeader(String& response, int code, const char* content_type, size_t contentLength) {

                              ^

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:440:30: error: expected initializer before '<' token

 void ESP8266WebServerTemplate<ServerType>::send(int code, const char* content_type, const String& content) {

                              ^

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:452:30: error: expected initializer before '<' token

 void ESP8266WebServerTemplate<ServerType>::send_P(int code, PGM_P content_type, PGM_P content) {

                              ^

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:470:30: error: expected initializer before '<' token

 void ESP8266WebServerTemplate<ServerType>::send_P(int code, PGM_P content_type, PGM_P content, size_t contentLength) {

                              ^

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:482:30: error: expected initializer before '<' token

 void ESP8266WebServerTemplate<ServerType>::send(int code, char* content_type, const String& content) {

                              ^

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:487:30: error: expected initializer before '<' token

 void ESP8266WebServerTemplate<ServerType>::send(int code, const String& content_type, const String& content) {

                              ^

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:492:30: error: expected initializer before '<' token

 void ESP8266WebServerTemplate<ServerType>::sendContent(const String& content) {

                              ^

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:511:30: error: expected initializer before '<' token

 void ESP8266WebServerTemplate<ServerType>::sendContent_P(PGM_P content) {

                              ^

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:516:30: error: expected initializer before '<' token

 void ESP8266WebServerTemplate<ServerType>::sendContent_P(PGM_P content, size_t size) {

                              ^

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:533:32: error: expected initializer before '<' token

 String ESP8266WebServerTemplate<ServerType>::credentialHash(const String& username, const String& realm, const String& password)

                                ^

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:543:30: error: expected initializer before '<' token

 void ESP8266WebServerTemplate<ServerType>::_streamFileCore(const size_t fileSize, const String &fileName, const String &contentType)

                              ^

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:556:39: error: expected initializer before '<' token

 const String& ESP8266WebServerTemplate<ServerType>::pathArg(unsigned int i) const { 

                                       ^

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:563:39: error: expected initializer before '<' token

 const String& ESP8266WebServerTemplate<ServerType>::arg(const String& name) const {

                                       ^

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:576:39: error: expected initializer before '<' token

 const String& ESP8266WebServerTemplate<ServerType>::arg(int i) const {

                                       ^

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:583:39: error: expected initializer before '<' token

 const String& ESP8266WebServerTemplate<ServerType>::argName(int i) const {

                                       ^

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:590:29: error: expected initializer before '<' token

 int ESP8266WebServerTemplate<ServerType>::args() const {

                             ^

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:595:30: error: expected initializer before '<' token

 bool ESP8266WebServerTemplate<ServerType>::hasArg(const String& name) const {

                              ^

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:609:39: error: expected initializer before '<' token

 const String& ESP8266WebServerTemplate<ServerType>::header(const String& name) const {

                                       ^

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:618:30: error: expected initializer before '<' token

 void ESP8266WebServerTemplate<ServerType>::collectHeaders(const char* headerKeys[], const size_t headerKeysCount) {

                              ^

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:630:39: error: expected initializer before '<' token

 const String& ESP8266WebServerTemplate<ServerType>::header(int i) const {

                                       ^

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:637:39: error: expected initializer before '<' token

 const String& ESP8266WebServerTemplate<ServerType>::headerName(int i) const {

                                       ^

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:644:29: error: expected initializer before '<' token

 int ESP8266WebServerTemplate<ServerType>::headers() const {

                             ^

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:649:30: error: expected initializer before '<' token

 bool ESP8266WebServerTemplate<ServerType>::hasHeader(const String& name) const {

                              ^

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:658:39: error: expected initializer before '<' token

 const String& ESP8266WebServerTemplate<ServerType>::hostHeader() const {

                                       ^

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:663:30: error: expected initializer before '<' token

 void ESP8266WebServerTemplate<ServerType>::onFileUpload(THandlerFunction fn) {

                              ^

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:668:30: error: expected initializer before '<' token

 void ESP8266WebServerTemplate<ServerType>::onNotFound(THandlerFunction fn) {

                              ^

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:673:30: error: expected initializer before '<' token

 void ESP8266WebServerTemplate<ServerType>::_handleRequest() {

                              ^

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:705:30: error: expected initializer before '<' token

 void ESP8266WebServerTemplate<ServerType>::_finalizeResponse() {

                              ^

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:712:32: error: expected initializer before '<' token

 String ESP8266WebServerTemplate<ServerType>::responseCodeToString(const int code) {

                                ^

In file included from C:\Users\Finnt\Desktop\marquee-scroller-master\marquee\marquee.ino:22:0:

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/Parsing-impl.h:64:30: error: expected initializer before '<' token

 bool ESP8266WebServerTemplate<ServerType>::_parseRequest(ClientType& client) {

                              ^

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/Parsing-impl.h:266:30: error: expected initializer before '<' token

 bool ESP8266WebServerTemplate<ServerType>::_collectHeader(const char* headerName, const char* headerValue) {

                              ^

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/Parsing-impl.h: In member function 'void storeArgHandler<ServerType>::operator()(String&, String&, const String&, int, int, int, int)':

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/Parsing-impl.h:281:11: error: 'ESP8266WebServerTemplate' was not declared in this scope

     key = ESP8266WebServerTemplate<ServerType>::urlDecode(data.substring(pos, key_end_pos));

           ^

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/Parsing-impl.h:281:11: note: suggested alternative:

In file included from C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:27:0,

                 from C:\Users\Finnt\Desktop\marquee-scroller-master\marquee\marquee.ino:19:

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/ESP8266WebServer.h:68:7: note:   'esp8266webserver::ESP8266WebServerTemplate'

 class ESP8266WebServerTemplate;

       ^

In file included from C:\Users\Finnt\Desktop\marquee-scroller-master\marquee\marquee.ino:22:0:

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/Parsing-impl.h:281:46: error: expected primary-expression before '>' token

     key = ESP8266WebServerTemplate<ServerType>::urlDecode(data.substring(pos, key_end_pos));

                                              ^

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/Parsing-impl.h:281:47: error: '::urlDecode' has not been declared

     key = ESP8266WebServerTemplate<ServerType>::urlDecode(data.substring(pos, key_end_pos));

                                               ^

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/Parsing-impl.h:283:50: error: expected primary-expression before '>' token

       value = ESP8266WebServerTemplate<ServerType>::urlDecode(data.substring(equal_index + 1, next_index));

                                                  ^

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/Parsing-impl.h:283:51: error: '::urlDecode' has not been declared

       value = ESP8266WebServerTemplate<ServerType>::urlDecode(data.substring(equal_index + 1, next_index));

                                                   ^

In file included from C:\Users\Finnt\Desktop\marquee-scroller-master\marquee\marquee.ino:22:0:

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/Parsing-impl.h: At global scope:

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/Parsing-impl.h:296:30: error: expected initializer before '<' token

 void ESP8266WebServerTemplate<ServerType>::_parseArguments(const String& data) {

                              ^

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/Parsing-impl.h:309:29: error: expected initializer before '<' token

 int ESP8266WebServerTemplate<ServerType>::_parseArgumentsPrivate(const String& data, std::function<void(String&,String&,const String&,int,int,int,int)> handler) {

                             ^

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/Parsing-impl.h:361:30: error: expected initializer before '<' token

 void ESP8266WebServerTemplate<ServerType>::_uploadWriteByte(uint8_t b){

                              ^

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/Parsing-impl.h:372:33: error: expected initializer before '<' token

 uint8_t ESP8266WebServerTemplate<ServerType>::_uploadReadByte(ClientType& client){

                                 ^

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/Parsing-impl.h:383:30: error: expected initializer before '<' token

 bool ESP8266WebServerTemplate<ServerType>::_parseForm(ClientType& client, const String& boundary, uint32_t len){

                              ^

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/Parsing-impl.h:601:32: error: expected initializer before '<' token

 String ESP8266WebServerTemplate<ServerType>::urlDecode(const String& text)

                                ^

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/Parsing-impl.h:633:30: error: expected initializer before '<' token

 bool ESP8266WebServerTemplate<ServerType>::_parseFormUploadAborted(){

                              ^

In file included from C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/ESP8266WebServer.h:260:0,

                 from C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:27,

                 from C:\Users\Finnt\Desktop\marquee-scroller-master\marquee\marquee.ino:19:

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/Parsing-impl.h: In instantiation of 'bool esp8266webserver::ESP8266WebServerTemplate<ServerType>::_parseRequest(esp8266webserver::ESP8266WebServerTemplate<ServerType>::ClientType&) [with ServerType = WiFiServer; esp8266webserver::ESP8266WebServerTemplate<ServerType>::ClientType = WiFiClient]':

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:335:41:   required from 'void esp8266webserver::ESP8266WebServerTemplate<ServerType>::handleClient() [with ServerType = WiFiServer]'

C:\Users\Finnt\Desktop\marquee-scroller-master\marquee\marquee.ino:497:25:   required from here

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/Parsing-impl.h:186:101: error: call of overloaded 'readBytesWithTimeout(esp8266webserver::ESP8266WebServerTemplate<WiFiServer>::ClientType&, uint32_t&, String&, int)' is ambiguous

            (   !readBytesWithTimeout<ServerType>(client, contentLength, plainBuf, HTTP_MAX_POST_WAIT)

                                                                                                     ^

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/Parsing-impl.h:186:101: note: candidates are:

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/Parsing-impl.h:43:13: note: bool esp8266webserver::readBytesWithTimeout(typename ServerType::ClientType&, size_t, String&, int) [with ServerType = WiFiServer; typename ServerType::ClientType = WiFiClient; size_t = unsigned int]

 static bool readBytesWithTimeout(typename ServerType::ClientType& client, size_t maxLength, String& data, int timeout_ms)

             ^

In file included from C:\Users\Finnt\Desktop\marquee-scroller-master\marquee\marquee.ino:22:0:

C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/Parsing-impl.h:43:13: note: bool readBytesWithTimeout(typename ServerType::ClientType&, size_t, String&, int) [with ServerType = WiFiServer; typename ServerType::ClientType = WiFiClient; size_t = unsigned int]

 static bool readBytesWithTimeout(typename ServerType::ClientType& client, size_t maxLength, String& data, int timeout_ms)

             ^

Multiple libraries were found for "WiFiServer.h"

 Used: C:\Users\Finnt\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WiFi

 Not used: C:\Program Files (x86)\Arduino\libraries\WiFi

exit status 1

Error compiling for board LOLIN(WEMOS) D1 mini Lite.



This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by finnie2006** [comment]
this is good right? and do i need to do something more because i have 2 modules



Executable segment sizes:
IROM   : 425668          - code in flash         (default or ICACHE_FLASH_ATTR) 
IRAM   : 28716   / 32768 - code in IRAM          (ICACHE_RAM_ATTR, ISRs...) 
DATA   : 1420  )         - initialized variables (global, static) in RAM/HEAP 
RODATA : 10512 ) / 81920 - constants             (global, static) in RAM/HEAP 
BSS    : 33808 )         - zeroed variables      (global, static) in RAM/HEAP 
Sketch uses 466316 bytes (48%) of program storage space. Maximum is 958448 bytes.
Global variables use 45740 bytes (55%) of dynamic memory, leaving 36180 bytes for local variables. Maximum is 81920 bytes.

**Comment by Qrome** [comment]
Yeah,  think you got it loaded.   Now when you have it powered up, you should see it show up as an Access Point.  You should be able to connect to it and view the configuration pages.
