### ISSUE TITLE
Decimal places in temp and wind speed

### ISSUE THREAD

**Issue by fixyourlan** [Qrome/marquee-scroller#16]
Great case and device,  but my display is a little longer then the space in the case. I didn't buy the ones from Amazon you had the link too. I already had 4 of the quad displays from China sitting on my bench.  Another 2mm on the long side next to the white edge of the LED's the part that touches the thin display would work for my displays. The PCB the LED's mount to fits ok, its just the LED module is a little bigger I guess from other mfgs.  

Can you mod the code to make the temp read just 78F instead of 78.7F and the wind speed 9 instead of 9.77.  No one can tell the difference with fractions of a degree and speed! I would make it easier to read as it scrolls by. I don't know why WU publishes it that way, but if you could fix it it would be a lot better!

**Comment by Qrome** [comment]
This is actually something I had considered a while back.  I added additional methods to the WU client to get the rounded values.   I have updated the latest release of 1.8 to round to the nearest whole values for Temp and Wind.
