### ISSUE TITLE
Weather Error: Weather Data Error: HTTP/1.1 401 Unauthorized

### ISSUE THREAD

**Issue by trombose009** [Qrome/marquee-scroller#160]
cannot configure weather api correctly. I did enter the api key and the number of my city. But still this error...
Weather Error: Weather Data Error: HTTP/1.1 401 Unauthorized

 :( 
any ideas?
Greetings

**Comment by Qrome** [comment]
401 means that the authorization has failed with the weather service.   Make sure your API key is active and correct.

**Comment by trombose009** [comment]
hm, I can double check that. but i have made an account and copy and paste the key.... hm

**Comment by Boshimanu** [comment]
Same Issue here, I've recreated the key twice, but nothing. Could be a problem with the site, maybe a pay wall?
