### ISSUE TITLE
Right one?

### ISSUE THREAD

**Issue by finnie2006** [Qrome/marquee-scroller#162]
is this the right wemos
https://opencircuit.nl/Product/WeMos-D1-mini-V3.1-Wifi-Module

**Comment by Qrome** [comment]
I have not used the V3 but I have been told others have used them without problem.   Were you able to source from the links in the directions?

**Comment by finnie2006** [comment]
what do u mean with
Were you able to source from the links in the directions?

**Comment by Qrome** [comment]
Sorry, are you able to find the same wemos d1 provided in the links provided?

**Comment by finnie2006** [comment]
I bought the one i sended you i will get it in some hours
i hope it works

**Comment by finnie2006** [comment]
i recived it i am flashing the code rn

**Comment by finnie2006** [comment]
The wemos dindt work great maybe wrong soldering
But the nodemcu worked great
