### ISSUE TITLE
Using esptool.py ?

### ISSUE THREAD

**Issue by marcoscv-work** [Qrome/marquee-scroller#169]
Hey guys, this is more a question, could we use `esptool` to write compile files? for example:

`esptool.py -p /dev/tty.usbserial-1440 --baud 115200 write_flash -fs 1MB -fm dout -ff 40m 0x0 marquee.ino.d1_mini_2.16.bin`

It should work?
Thanks

**Comment by radimkarnis** [comment]
Sure, a simple `esptool.py write_flash 0x0 marquee.ino.d1_mini_2.16.bin` works just fine!

**Comment by marcoscv-work** [comment]
thanks!
