### ISSUE TITLE
Issues with dot matrix module

### ISSUE THREAD

**Issue by ayush758** [Qrome/marquee-scroller#174]
I am using a 1x4 dot matrix module, the code compiles successfully but the matrix module has all its led's lit up, and I cannot seem to connect to the web interface as well, when I enter the network SSID and password the wemos shows up in my routers address list but when I try to access the IP it says website cannot be reached. I have double-checked the connections and the code/libraries can someone guide me towards a fix?

**Comment by Qrome** [comment]
Make sure you turn in 1M SPIFFS -- this is so it can store settings in memory.
From the Readme:
Set Flash Size to 1M SPIFFS -- this project requires SPIFFS for saving and reading configuration settings.

**Comment by ayush758** [comment]
okay so I had to change my port number for it to work, might be port 80 was blocked. But now I am having another issue
Weather Error: Weather Data Error: HTTP/1.1 401 Unauthorized

**Comment by Qrome** [comment]
Make sure you have activated your weather key.   401 response is from the weather service saying you are not authorised.
