### ISSUE TITLE
News Feed Problem

### ISSUE THREAD

**Issue by tadder** [Qrome/marquee-scroller#177]
Thank you for the information that I needed to load the latest issue of the software. Quite right, and news is now working fine, however the display is now up-side-down, is there a way to alter this?

**Comment by Qrome** [comment]
Line 96 of the Settings.h file.

 /* set ledRotation for LED Display panels (3 is default)
0: no rotation
1: 90 degrees clockwise
2: 180 degrees
3: 90 degrees counter clockwise (default)
*/
int ledRotation = 3;
