### ISSUE TITLE
Degree Sign missing

### ISSUE THREAD

**Issue by njordan77** [Qrome/marquee-scroller#180]
I guess its no real issue but i was asking myself why there is no °Sign @temperatures. Is it a matter of place on the display?
The reason is that people first looking at this great implementation are little confused about the temperature displayed.

Is there a plan or a reason for not using the ° sign?
Thanks a lot
Norbert
btw, very nice project, really love your implementation....

**Comment by Qrome** [comment]
The fonts that are used do not have that symbol. Or it would have been used. Sorry if it confuses people. But that is how it is right now.

**Comment by brianmiller1956** [comment]
Hi, Sorry to butt in, I added the degree symbol to both the present temperature and the hi/lo temp, the lines just need +char(247) adding thus, it is included in the glcdfont file.
Brian.

if (SHOW_CITY) {
        msg += weatherClient.getCity(0) + ".  ";//added full stop to place name
      }
      msg += temperature + char(247) + getTempSymbol() + "  "; //added char(247) degree symbol

      //show high/low temperature, added space to Hi/Lo, Humidity, Barometer
      if (SHOW_HIGHLOW) {
        msg += "High/Low: " + weatherClient.getHigh(0) + "/" + weatherClient.getLow(0) + char(247) + getTempSymbol() + "  ";//added char(247) degree symbol
      }

Sent from Mail for Windows 10

**Comment by njordan77** [comment]
wow, thanks a lot for the feedback. i did not want to put a request on the table, but more understand if it was a matter of discussion or why its not implemented.

@Qrome would it be possible to add the code from @brianmiller1956 and provide a new BIN version. That would help me to not get stuck with libraries,..... 

Many Thanks
Norbert

**Comment by brianmiller1956** [comment]
Hi Norbert,
Sorry to butt in, I added the degree symbol a while ago from another fork, it is just a case of adding +char(247) in two places the first puts it in the present temp the second the hi/lo temp. The font file does have this defined. I cant give you the line numbers but it is easy to find in the main loop.

msg += temperature + char(247) + getTempSymbol() + "  "; //added char(247) degree symbol

      //show high/low temperature, added space to Hi/Lo, Humidity, Barometer
      if (SHOW_HIGHLOW) {
        msg += "High/Low: " + weatherClient.getHigh(0) + "/" + weatherClient.getLow(0) + char(247) + getTempSymbol() + "  ";//added char(247) degree symbol
      }

Brian

Sent from Mail for Windows 10

From: njordan77
Sent: 20 March 2021 21:33
To: Qrome/marquee-scroller
Cc: Subscribed
Subject: [Qrome/marquee-scroller] Degree Sign missing (#180)

I guess its no real issue but i was asking myself why there is no °Sign @temperatures. Is it a matter of place on the display?
The reason is that people first looking at this great implementation are little confused about the temperature displayed.
Is there a plan or a reason for not using the ° sign?
Thanks a lot
Norbert
btw, very nice project, really love your implementation....

**Comment by Qrome** [comment]
I will take a look at it but I will probably be adding it to the function get temperature symbol so it doesn't have to be injected everywhere.

**Comment by Qrome** [comment]
Thanks by the way.   I am testing it by just adding it to the following function:

`String getTempSymbol() {
  String rtnValue = "F";
  if (IS_METRIC) {
    rtnValue = "C";
  }
  return char(247) + rtnValue;
}`

**Comment by brianmiller1956** [comment]
Many thanks, this is a really great project, I am a newcomer to the arduino ide but have learnt a lot from this project, it really is easy to add cosmetic changes.
P.s. any chance of adding sunrise/sunset times to the weather?

**Comment by Qrome** [comment]
@njordan77 -- thanks for the info.   

I have created a 3.17 branch with binaries that have the updated degree symbol.  I have tested it in both the web interface and in the clock.  I have also updated it for the wide clock version and tested there.   This has not yet been merged to master, but you can get the binary and see the changes here:

https://github.com/Qrome/marquee-scroller/tree/release/3.17

As for adding lots of display options -- I kind of went down that route in the beginning, but have been trying to simplify a bit.   I will consider it.  Thanks again.

**Comment by brianmiller1956** [comment]
Hi, just to update you, I added your modification for the degree symbol and removed mine, it works in the scroller fine but the web interface doesn’t like it, I am using an Apple iPad and have tried both safari and google chrome with the same results. I have attached screen shot.

**Comment by Qrome** [comment]
@brianmiller1956 -- yeah, sorry about that.  The code snip I shared above was not what ended up in the 3.17 branch.  This is what I ended up doing after testing the web interface.

String getTempSymbol() {
  return getTempSymbol(false);
}

String getTempSymbol(bool forWeb) {
  String rtnValue = "F";
  if (IS_METRIC) {
    rtnValue = "C";
  }
  if (forWeb) {
    rtnValue = "°" + rtnValue;
  } else {
    rtnValue = char(247) + rtnValue;
  }
  return rtnValue;
}

Then in the two lines where it calls to get the temp symbol for the web interface I updated it to:

    html += temperature + " " + getTempSymbol(true) + "<br>";
    html += weatherClient.getHigh(0) + "/" + weatherClient.getLow(0) + " " + getTempSymbol(true) + "<br>";


I hope that helps.   Thanks again for sharing.

**Comment by brianmiller1956** [comment]
Just to confirm, I have added these changes and they work well, many thanks.

**Comment by Qrome** [comment]
@brianmiller1956 thanks again.

**Comment by njordan77** [comment]
Thanks to both of you to make this happen so quick!!!!!!
I'm curious to see how the alignment works when there is a two digits temp to be presented. Right now its +2°C...so plenty of space on the wide display. guess will be crowded when it reaches a second digit.

**Comment by Qrome** [comment]
@njordan77 -- in the 3.17 branch I removed one of the spaces between the time and the temp -- so it should be just fine.  I live a place that we see things like 114°F -- so that now adds another character in there.  It should be fine though.
