### ISSUE TITLE
Doesnt compile now :(

### ISSUE THREAD

**Issue by laneyweb** [Qrome/marquee-scroller#186]
I had this working a few weeks ago. I tried to recompile today and get this:
anyone offer any help please?

```
C:\Stuff\Electronics\marquee-scroller-master\marquee\NewsApiClient.cpp: In member function 'void NewsApiClient::updateNews()':
NewsApiClient.cpp:49:13: error: call to 'HTTPClient::begin' declared with attribute error: obsolete API, use ::begin(WiFiClient, url)
   49 |   http.begin(apiGetData);
      |   ~~~~~~~~~~^~~~~~~~~~~~
C:\Stuff\Electronics\marquee-scroller-master\marquee\PiHoleClient.cpp: In member function 'void PiHoleClient::getGraphData(String, int)':
PiHoleClient.cpp:155:13: error: call to 'HTTPClient::begin' declared with attribute error: obsolete API, use ::begin(WiFiClient, url)
  155 |   http.begin(apiGetData);
      |   ~~~~~~~~~~^~~~~~~~~~~~
C:\Stuff\Electronics\marquee-scroller-master\marquee\BitcoinApiClient.cpp: In member function 'void BitcoinApiClient::updateBitcoinData(String)':
BitcoinApiClient.cpp:44:13: error: call to 'HTTPClient::begin' declared with attribute error: obsolete API, use ::begin(WiFiClient, url)
   44 |   http.begin(apiGetData);
      |   ~~~~~~~~~~^~~~~~~~~~~~
C:\Stuff\Electronics\marquee-scroller-master\marquee\PiHoleClient.cpp: In member function 'void PiHoleClient::getTopClientsBlocked(String, int, String)':
PiHoleClient.cpp:105:13: error: call to 'HTTPClient::begin' declared with attribute error: obsolete API, use ::begin(WiFiClient, url)
  105 |   http.begin(apiGetData);// get the result
      |   ~~~~~~~~~~^~~~~~~~~~~~
C:\Stuff\Electronics\marquee-scroller-master\marquee\PiHoleClient.cpp: In member function 'void PiHoleClient::getPiHoleData(String, int)':
PiHoleClient.cpp:38:13: error: call to 'HTTPClient::begin' declared with attribute error: obsolete API, use ::begin(WiFiClient, url)
   38 |   http.begin(apiGetData);// get the result
      |   ~~~~~~~~~~^~~~~~~~~~~~
exit status 1
call to 'HTTPClient::begin' declared with attribute error: obsolete API, use ::begin(WiFiClient, url)

```

**Comment by Qrome** [comment]
What board do you have selected and what version of ESP8266 core platform do you have installed?

**Comment by laneyweb** [comment]
Hi there, thank you for your reply!
I have a Wemos D1 Mini and have the board: LOLIN Wemos D1 R1
I am not sure how to check the ESP8266 platform, sorry, are you able to point me to where I should look in the Arduino App?

**Comment by Qrome** [comment]
Under the Board Manager -- filter it on esp8266 -- this should show you what ESP8266 core version you have installed.  My guess is you have upgraded.  This project was written for version 2.5.2.   

![image](https://user-images.githubusercontent.com/32021227/119240233-2e3d5700-bb03-11eb-862c-744ecc785efe.png)

**Comment by brianmiller1956** [comment]
Hi, I saw this post and have checked this, I updated the esp8266 core to v3.0.0 earlier this week and also found that marquee scroller doesn’t compile and gives the identical errors, I have reinstalled v2.7.4 and it compiled first time. Hope this helps.

**Comment by laneyweb** [comment]
Thank you very much both of you. I had indeed upgraded to 3... - installed 2.5.2 again and all is well :)

Thanks again for both of your prompt replies.

**Comment by brianmiller1956** [comment]
Hi, I went back to 2.7.4 the previous version, might be better than 2.5.2, it does compile ok.
