### ISSUE TITLE
Hour showing wrongly

### ISSUE THREAD

**Issue by xavisaurus** [Qrome/marquee-scroller#189]
The HH is showing as an overlapped character with 0 and somehting else. instead of 2 characters.  Whether I change the format to HH:MM, HH:MM:SS or HH:MM Temperature or set to military time, it has the same error

**Comment by victor7376** [comment]
Did you keep everything to default and upload via the instructions given ??

**Comment by vk2zaz** [comment]
Hi I changed 1 line
	String hourMinutes(boolean isRefresh) {
	  if (IS_24HOUR) {
	//ADDED THIS LINE    
        return TimeDB.zeroPad(hour()) + secondsIndicator(isRefresh) + TimeDB.zeroPad(minute());
	 // COMMENTED THIS LINE return hour() + secondsIndicator(isRefresh) + TimeDB.zeroPad(minute());
	  } else {
	    return hourFormat12() + secondsIndicator(isRefresh) + TimeDB.zeroPad(minute());
	  }
	}
Geoff

**Comment by dreiber999** [comment]
This change fixes the issue with the hours displayed when using the 24 hour clock option, but I still have a problem with the hours displayed when using the 12 hour clock option...  It shows some odd characters.

**Comment by victor7376** [comment]
> This change fixes the issue with the hours displayed when using the 24 hour clock option, but I still have a problem with the hours displayed when using the 12 hour clock option... It shows some odd characters.

Can you post what your clock shows please?

**Comment by xavisaurus** [comment]
Hi, before the code revision, my clock was showing symbols, like spade, diamond, club, heart, smiley face etcetc.

**Comment by dreiber999** [comment]
Here is what is displayed at 9:57 am and 11:04 am

https://user-images.githubusercontent.com/1891718/154862417-e8d22293-e9f9-4472-9efa-1dd589ee5f4e.jpg

https://user-images.githubusercontent.com/1891718/154862447-24e99e2d-24d5-477b-95c2-9bdcc9fcad15.jpg

**Comment by victor7376** [comment]
> Here is what is displayed at 9:57 am and 11:04 am
> 
> https://user-images.githubusercontent.com/1891718/154862417-e8d22293-e9f9-4472-9efa-1dd589ee5f4e.jpg
> 
> https://user-images.githubusercontent.com/1891718/154862447-24e99e2d-24d5-477b-95c2-9bdcc9fcad15.jpg

Thank you for the images, which version of the code are you using?

**Comment by dreiber999** [comment]
Version 2.18, downloaded last week.

**Comment by victor7376** [comment]
> Version 2.18, downloaded last week.

I’m going to upgrade mine this week & see if I have the same issue.  If not I’ll post the versions of the software I’m using.

**Comment by victor7376** [comment]
Found the issue. 

If you have 8266 ESP package installed 2.5.2 the clock will work perfectly with the hours 12/24.  But if you install the latest versions 3.0.2 you will get the symbols instead of the 12 hours clock.

I'm not sure when the changes happened, so you could try upgrading the ESP package until you see the 12 hour clock change the symbols.  Then just revert to the older version.

As soon as I reverted from the latest version to the older version the clock worked fine.

Hope this helps.

**Comment by victor7376** [comment]
UPDATE:

With the help of a kind person from within the ESP8266 coders, I've been able to update to ESP8266 core to 3.0.2 & correctly show the Hours in 12 hour format.  To make it compile I also had to change Bitcoin, Pihole & News to use the updated coding as it was saying the old coding was obsolete.

I have forked it and uploaded the changes if anyone is interested.

**Comment by dreiber999** [comment]
It's beautiful!  Thanks.
