### ISSUE TITLE
rounding min / max

### ISSUE THREAD

**Issue by omegaxxl** [Qrome/marquee-scroller#191]
Hello,
it's a nice project. But I would like the min / max temperature only for one place after the comma. For example 26.2C/ 28.4C. Can anyone advise me where and what to change?
Thank you for your help and I apologize for my English

**Comment by victor7376** [comment]
If you mean rounding the temp high and low you would need to recode the openweather cpp & h with new commands then add the new commands into the marquee.

This kind of coding may work (for example):

Adding into openweathermapclient.cpp:

String OpenWeatherMapClient::getHighRounded(int index)
{
return roundValue(getHigh(index));
}

Then adding in openweathermapclient.h under Public:

String getHighRounded(int index);

Then changing at line 398 in marquee:

msg += “High/Low:” + weatherClient.getHighRounded(0) +

This should give you rounded temp for High in your area, just do the same for Low in the above example.

**Comment by omegaxxl** [comment]
Hello,
big thanks for the advice. I was able to edit the code.
Just please for more advice on how to show the temperature max / min to one decimal place (25.3C)
Thank you very much for your help.

**Comment by victor7376** [comment]
I had a quick look and there are coding references for putting a temperature to just one decimal place within coding.  The references are on the official arduino forum.
