### ISSUE TITLE
time is not updated

### ISSUE THREAD

**Issue by terragady** [Qrome/marquee-scroller#197]
Time is not updating, after turning on it just starts from 0:00 and do not give any errors. Is it timedb api problem or something else?

**Comment by roelleke** [comment]
Look at issue #194 No more time. [](https://github.com/Qrome/marquee-scroller/issues/194)

**Comment by Qrome** [comment]
Release has fix:  https://github.com/Qrome/marquee-scroller/releases/tag/Scroller_V2.18
