### ISSUE TITLE
Two small typos

### ISSUE THREAD

**Issue by tobiasboyd** [Qrome/marquee-scroller#2]
I did notice the web client forms have a couple of little typos:

"Select News Srouce"

https://github.com/Qrome/marquee-scroller/blob/856bad067daba28e0fcabe2dce6dee7e187cbcb1/marquee/marquee.ino#L105

and

"Celcius" instead of Celsius

https://github.com/Qrome/marquee-scroller/blob/856bad067daba28e0fcabe2dce6dee7e187cbcb1/marquee/marquee.ino#L103

**Comment by Qrome** [comment]
Thanks, I will put the changes in 1.1 branch.
