### ISSUE TITLE
Celsius and mph ?

### ISSUE THREAD

**Issue by nikki-reprap** [Qrome/marquee-scroller#20]
Hi is it possible to display  Celsius and mph instead of  Celsius and kph  ?

Thanks Nikki

**Comment by Qrome** [comment]
Nikki -- please share what version you are running and also under.  I don't quite understand your request here.

**Comment by Qrome** [comment]
Right now if you set it for Metric -- you get values in metric.

**Comment by nikki-reprap** [comment]
I am running version 1.8 on a esp8266  I am looking  to be able to display temperature in Celsius and wind speed in mph mixing imperial and metric

Thanks

**Comment by Qrome** [comment]
I understand now.   One of my goals is to not have the settings too convoluted and and packed with edge case requests.  I do not think this is one I would include in the code base.

However, you could probably easily modify the weather client in your own version to convert the response from openWeather and convert it and display it in your own version.
