### ISSUE TITLE
Time on the clock is wrong

### ISSUE THREAD

**Issue by LordOfStrings** [Qrome/marquee-scroller#204]
Hey , So there seems to be an issue with the scroller where the time always starts from 12:00 AM for some reason, I checked the API key and also checked if the API was begin called and yes it was , any help would be appreciated

Thank you.

**Comment by Qrome** [comment]
Did you check the latest release that fixes that?  https://github.com/Qrome/marquee-scroller/releases/tag/Scroller_V2.18
