### ISSUE TITLE
Time sync doesnt seem to happen any longer

### ISSUE THREAD

**Issue by pepperm2** [Qrome/marquee-scroller#205]
For some reason, both of my Marquee scrollers have lost the ability to sync their time with TimeZoneDB. Has their time format changed or something?

I have tried reconfiguring and getting a new API key all without effect. WIFI connection works because weather information is collected but after reboot the time always starts at 12:00.

I am running V2.17 and here is the serial output from the ESP on boot (just the time and weather bits)...

Getting Weather Data
GET /data/2.5/group?id=2636841&units=metric&cnt=1&APPID=a1d9191c3ebeea047d01bf0d6ad6d6e8 HTTP/1.1
Waiting for data
Response Header: HTTP/1.1 200 OK
lat: 53.0042
lon: -2.1854
dt: 1634807354
city: Stoke-on-Trent
country: GB
temp: 7.28
humidity: 78
condition: Clear
wind: 3.20
direction: 308
weatherId: 800
description: clear sky
icon: 01d
timezone: 1

Updating Time...
News Data for 
Getting Time Data for 53.0042,-2.1854
GET /v2.1/get-time-zone?key=4LF2K49NG3KE&format=json&by=position&lat=53.0042&lng=-2.1854 HTTP/1.1
Waiting for data
{"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=l%2FjwYMn17%2FP8ajBET03MxV29F%2FLNNh4X9UTYVN%2BMWGM74aWat%2B7kf%2BulSx3heZacyPKIA6iarIBeq6d2DKWT1znmLc49KA0yPyjCK4dVJGme5m9aC2jHeV9WD%2FbX5XexnKvzk6Y%3D"}{"success_fraction":0,"report_to":"cf-nel","max_age":604800}{"status":"OK","message":"","countryCode":"GB","countryName":"United Kingdom","zoneName":"Europe\/London","abbreviation":"BST","gmtOffset":3600,"dst":"1","zoneStart":1616893200,"zoneEnd":1635642000,"nextAbbreviation":"GMT","timestamp":1634814316,"formatted":"2021-10-21 11:05:16"}

firstEpoch is: 20
Version: 2.17

I note that the data stream above shows the correct time (11:06:16) but this does not get displayed on the scroller.

Has anyone any clues why this has started to happen (a couple of weeks now).

Mark

**Comment by colsen2715** [comment]
V3.1 still has the problem.

**Comment by Boshimanu** [comment]
Hello, 
I have the same issue, but now in 2025, the last update is from January 2023.
Does anyone at the time present have the same issue?
Thanks🙏

**Comment by G6EJD** [comment]
If I remember correctly the code uses a time server/service that is no-longer in use; mainly for DST. It should be really easy to replace the time code with the ESP time library. That didn't exist when the code was created.

**Comment by Boshimanu** [comment]
An Update? 😁 Thanks🙏

**Comment by pepperm2** [comment]
Has anyone solved this issue yet please? I have 3 weather clocks that are all exhibiting the time issue now. Sadly I'm not that code proficient to be able to re-write the code myself. I am running V3.03 code. and get the following error: Weather Data Error: HTTP/1.1 401 Unauthorized

If there isnt a fix possible, does anyone know of any other code that can use this hardware configuration for, maybe another purpose?

**Comment by colsen2715** [comment]
I get a message like Weather error abort. That prevents the time from
showing. I don’t have the time now to look at it. I am sure it’s the
message sent to get the weather. Google that and see if someone has the new
message.
