### ISSUE TITLE
TIMEZONE does not work for me

### ISSUE THREAD

**Issue by dj55nava** [Qrome/marquee-scroller#208]
A couple of days ago the time stopped working, it does not correspond to reality, I entered TIMEZONE and the API key had changed and even if I changed it, I did not get a result. Has it happened to someone? any solution? Thank you

**Comment by Qrome** [comment]
You can upgrade to the latest version.   There was a release to fix the TimeDB response API.   You can upgrade through the web interface by downloading the corresponding bin file or compile it on your own.  https://github.com/Qrome/marquee-scroller/releases/tag/Scroller_V2.18
