### ISSUE TITLE
Weather data failure

### ISSUE THREAD

**Issue by RCBock** [Qrome/marquee-scroller#209]
My Marquee stopped working around 12 PM on Sunday, October 31, 2021. I have already upgraded the software/firmware to 2.18. It has been working perfectly until now. Error states the "Weather Data Did Not Connect".

**Comment by Qrome** [comment]
Check your API key for the weather -- is it expired or blocked?  Make sure the endpoint is available from your network.

**Comment by RCBock** [comment]
Thanks for the quick response. Changed API and all seems to work now.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
