### ISSUE TITLE
invalid operands of types 'float' and 'long int' to binary 'operator%'

### ISSUE THREAD

**Issue by scaronex** [Qrome/marquee-scroller#212]
hello on software 2.16 my clock stopped working so I wanted to upload a newer one, but I have an error

C:\Users\scaro\Downloads\marquee-scroller-Scroller_V2.2\marquee\TimeClient.cpp: In member function 'long int TimeClient::getCurrentEpochWithUtcOffset()':

TimeClient.cpp:151:65: error: invalid operands of types 'float' and 'long int' to binary 'operator%'

  151 |   return round(getCurrentEpoch() + 3600 * myUtcOffset + 86400L) % 86400L;

      |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~~~~~~

      |               |                                                   |

      |               float                                               long int

C:\Users\scaro\Downloads\marquee-scroller-Scroller_V2.2\marquee\NewsApiClient.cpp: In member function 'void NewsApiClient::updateNews()':

NewsApiClient.cpp:49:13: error: call to 'HTTPClient::begin' declared with attribute error: obsolete API, use ::begin(WiFiClient, url)

   49 |   http.begin(apiGetData);

      |   ~~~~~~~~~~^~~~~~~~~~~~

C:\Users\scaro\Downloads\marquee-scroller-Scroller_V2.2\marquee\BitcoinApiClient.cpp: In member function 'void BitcoinApiClient::updateBitcoinData(String)':

BitcoinApiClient.cpp:44:13: error: call to 'HTTPClient::begin' declared with attribute error: obsolete API, use ::begin(WiFiClient, url)

   44 |   http.begin(apiGetData);

      |   ~~~~~~~~~~^~~~~~~~~~~~

exit status 1

invalid operands of types 'float' and 'long int' to binary 'operator%'

**Comment by Qrome** [comment]
Get the 2.18 update.  Also use the correct version of ESP8266 core as mentioned in the readme.md file.

**Comment by cyberrat14** [comment]
I have the same issue with the version 2.15 stop to working. But I'm unable to updload the version 2.18 into the Firmware Update

**Comment by Qrome** [comment]
Why can't you upload the 2.18 bin file?

**Comment by Qrome** [comment]
The issue created here was closed as it is resolved in release 2.18 -- if you have issues updating please compile it again.  There is no issue updating.
