### ISSUE TITLE
Timesync fails

### ISSUE THREAD

**Issue by bit4man** [Qrome/marquee-scroller#213]
I've run the marquee-scroller for more than a year, daily on my office desk, works perfectly. However, after a "reboot" today I am no longer getting time updates from dbtime. From the serial log:

Updating Time...
essful!
Getting Time Data for 38.8951,-77.0364
GET /v2.1/get-time-zone?key=XXXXXXXXXXX&format=json&by=position&lat=38.8951&lng=-77.0364 HTTP/1.1
Waiting for data
{"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=3xA7TA4vmTfDdrYzswiMDg0jCGwPwKbOYJuHnvBa9CIHsbVY1Ann8uZHUmKL1}

The Cloudflare URL above reports:

curl -v "https://a.nel.cloudflare.com/report/v3?s=3xA7TA4vmTfDdrYzswiMDg0jCGwPwKbOYJuHnvBa9CIHsbVY1Ann8uZHUmKL1"
*   Trying 2600:1901:0:47fc:::443...
* Connected to a.nel.cloudflare.com (2600:1901:0:47fc::) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/pki/tls/certs/ca-bundle.crt
*  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=gcp.nel.cloudflare.com
*  start date: Oct 22 13:27:56 2021 GMT
*  expire date: Jan 20 13:27:55 2022 GMT
*  subjectAltName: host "a.nel.cloudflare.com" matched cert's "a.nel.cloudflare.com"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x55c710b6dc30)
> GET /report/v3?s=3xA7TA4vmTfDdrYzswiMDg0jCGwPwKbOYJuHnvBa9CIHsbVY1Ann8uZHUmKL1 HTTP/2
> Host: a.nel.cloudflare.com
> user-agent: curl/7.76.1
> accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
< HTTP/2 405 
< content-length: 0
< date: Tue, 09 Nov 2021 16:00:17 GMT
< via: 1.1 google
< alt-svc: clear
< 
* Connection #0 to host a.nel.cloudflare.com left intact

HTTP-405 is "method not allowed".

**Comment by Qrome** [comment]
Have you tried latest version of 2.18 that was released Oct 10th to fix this?
https://github.com/Qrome/marquee-scroller/releases/tag/Scroller_V2.18

**Comment by bit4man** [comment]
/me DUH
I'd done an update (I thought) but it turns out I just used my old version. 2.18 reset most of my settings, but it's getting the date/time now. Thanks.
