### ISSUE TITLE
Did not recognize fall back to Standard Time

### ISSUE THREAD

**Issue by pmastren** [Qrome/marquee-scroller#215]
My units are still showing Daylight Saving Time and so they are all one hour ahead.  My OpenWeatherMap City ID is 4699066 (Houston, TX, USA)

**Comment by Qrome** [comment]
Check the call to TimeDB -- that is where the timezone is given.

**Comment by pmastren** [comment]
$ curl 'http://api.timezonedb.com/v2.1/get-time-zone?key=XXXXXXXXXXXX&format=json&by=position&lat=29.7633&lng=-95.3633'
{"status":"OK","message":"","countryCode":"US","countryName":"United States","zoneName":"America\/Chicago","abbreviation":"CST","gmtOffset":-21600,"dst":"0","zoneStart":1636268400,"zoneEnd":1647158400,"nextAbbreviation":"CDT","timestamp":1636558013,"formatted":"2021-11-10 15:26:53"}

This is returning the correct time, but the unit is displaying 16:26.

**Comment by pmastren** [comment]
I haven't had a lot of time to work on this, but I've just discovered that the time is not updating at all.  After a power cycle, the date starts at Jan 1 1970 and never updates

**Comment by Qrome** [comment]
The fix release 2.18 was updated and posted over a month ago.   This will fix your issue @pmastren .

**Comment by pmastren** [comment]
My bad for not checking that first.  That fixed it.

Thank you
