### ISSUE TITLE
Question: .bin Creation

### ISSUE THREAD

**Issue by DirtMonger** [Qrome/marquee-scroller#216]
Has it been documented anywhere how to create our own .bin files for deployment of customized code?   Sorry if this is a stupid question, new to this stuff. 

Thanks.

**Comment by Qrome** [comment]
It is a standard feature of Arduino IDE.

**Comment by Qrome** [comment]
![image](https://user-images.githubusercontent.com/32021227/141243230-bcd053a6-7640-472e-94b7-8cdf46596a47.png)

**Comment by DirtMonger** [comment]
Thank you for the info!  This generated 2 more questions, if I may? 

- What is the difference between the mini and mini_wide .bins that you provide?  How are they different? 

- In Settings.h there is a variable numberOfVerticalDisplays.  Is a vertical stack actually supported?  Such as a 16x2 configuration?   If supported, what is maximum? 

Thank you!

**Comment by Qrome** [comment]
the wide is for the double wide 1 x 8.  I only compile bins for the 2 most common ways to run it and make it easy for people to upgrade using the standard bin compile.
The 2 x 16 -- I have never tried but should be supported.

**Comment by DirtMonger** [comment]
I'm so sorry, I wasn't clear in my first question.  In my house I have a 1x4, 1x8 and 1x16.   Were I to compile bins for each, what changes would I need to make for each.  That was why I asked what is the diff between your released bin files, albeit unclearly, lol.   The only place I see to indicate the matrix size is in the Settings.h file, but I think you stated that Settings.h is only read on the very first startup of the scroller.  So I wasn't sure if there were other places I need to change when I compile each .bin.  

Thank you.

**Comment by Qrome** [comment]
For all the settings that can be managed through the web interface, that is true.  However the number of displays is controlled by the Settings.h file.  So, edit the Settings.h file for each version you have before compiling them.
