### ISSUE TITLE
Time always Thursday, Jan 1, 12:00 AM

### ISSUE THREAD

**Issue by funk01** [Qrome/marquee-scroller#218]
Hi there,

the scroller worked fine for months, but now time starts at Thursday, Jan 1, 12:00 AM.

A new time API Key didn´t help. Location is and was correct. Version 2.16.

Any idea?
Best,
j.

**Comment by Qrome** [comment]
There was a new version posted to fix the issue on Oct, 10th.
https://github.com/Qrome/marquee-scroller/releases/tag/Scroller_V2.18

**Comment by funk01** [comment]
Thank you so much! Works like a charm!
