### ISSUE TITLE
Using 1602 LCD display instead of LED matrix

### ISSUE THREAD

**Issue by Arduinoslfan** [Qrome/marquee-scroller#22]
First of all great project.
Thanks for sharing.
I'm trying to use 1602 display.
So far I manage to display weather details on  one row.
I want to display news title , news description in another row.
I'm using following to display news but it only shows google news.
lcd.setCursor(0, 1);
lcd.println(NEWS_SOURCE);
what should be done to display news title + news description on display
Many thanks.

**Comment by Qrome** [comment]
Well, you need to look close at the NewsApiClient -- once you have that object and it has pulled the news from the sources, it will contain a list of the top 10 stories returned from your selected news source.   If you look at the NewsApiClient.h -- you will see 3 methods that allow you to pull exactly what you want -- you must provide the index (0 - 9) for the story you want to display.

Example:
newClient.getTitle(0)
newsClient.getDescription(0)
newsClient.getUrl(0)

The variable NEWS_SOURCE is just the string that tells the news client the source to pull from.

**Comment by Qrome** [comment]
Closing this item as it is just a question and not an issue.

**Comment by Arduinoslfan** [comment]
Many Thanks for your reply and its a big help for a newbie like me. 
I manged to display information on 16x2 display. 
After that, my next goal was to scroll text.
I managed to find a scroll text code. 
Tried only the scroll code with Nodemcu+LCD without including your program and it worked fine. 
However when I Included scroll text code into your program scrolling function wasnt working properly.
scrolling wasnt happenning all the time, It will stop for few seconds. Then the scrolling starts again. While the display is scrolling, I noticed blinking of esp12e blue led.
I tried with another scroll text code and results were same.
Please assist me to solve this issue. 
Thank you very much.
