### ISSUE TITLE
error compiling

### ISSUE THREAD

**Issue by degerang** [Qrome/marquee-scroller#225]
hello
can i remove bitcoin , newsapi, octoprint, pihole ?
i dont need them and they give compile error 

Lasse

**Comment by Qrome** [comment]
If you are getting compile errors then you are using the wrong version of ESP8266 core -- please read the readme.md for the versions of libraries.

**Comment by Qrome** [comment]
From the Readme file:

Compiling and Loading to Wemos D1
It is recommended to use Arduino IDE. You will need to configure Arduino IDE to work with the Wemos board and USB port and installed the required USB drivers etc.

USB CH340G drivers: https://sparks.gogo.co.nz/ch340.html
Enter http://arduino.esp8266.com/stable/package_esp8266com_index.json into Additional Board Manager URLs field. You can add multiple URLs, separating them with commas. This will add support for the Wemos D1 Mini to Arduino IDE.
Open Boards Manager from Tools > **Board menu and install esp8266 Core platform version 2.5.2**
Select Board: "LOLIN(WEMOS) D1 R2 & mini"
Set Flash Size to 1M SPIFFS -- this project requires SPIFFS for saving and reading configuration settings.
Select the Port from the tools menu.
