### ISSUE TITLE
 Clock stuck/frozen

### ISSUE THREAD

**Issue by liuxianhao666** [Qrome/marquee-scroller#229]
The clock often freezes after running for a few days and always stops when refreshing the data. I have this problem since version 2.15. Now I buy the hardware again and brush 2.18. This problem still exists. It was set according to your instructions, and I saw others ask the same question.

**Comment by liuxianhao666** [comment]
This problem does not occur again after using this version 2.19
[https://github.com/brainrecall/marquee-scroller](url)

**Comment by phenomeus** [comment]
is this coming to this original branch from the fork?

**Comment by Qrome** [comment]
Please note, as mentioned, this is not an official release.   As of yet, I have not been able to validate this.   Also, I have 5 clocks around my house and do not experience the freeze on the display.  I have a feeling it could be related to the version of ESP8266 core used or one of the other library files.

**Comment by phenomeus** [comment]
2.5.2 is the core in my case, so as wished in the readme

**Comment by Leonessa02016** [comment]
Hi. You mentioned version **2.19**. Where it is possible to download this new version ? I found only 2.18 one. Thanks.
