### ISSUE TITLE
Display issues

### ISSUE THREAD

**Issue by jimus888** [Qrome/marquee-scroller#231]
Hi,

Im having issues getting my screen to display correctly. Have attached some example pics and chip info.

For troubleshooting I have done the following:
- checked wiring
- checked esp8266 board library is 2.5.2
- checked flash size is 1M
- ran bin update to current version
- Tried rotating the output 

I can occasionally see the bottom row scrolling, then other lights will randomly light up, then all lights go off

Any ideas what is causing my problems?

![screen1](https://user-images.githubusercontent.com/75463370/150276228-713eafe3-b314-4efc-902e-d7425572c83c.jpg)
![screen2](https://user-images.githubusercontent.com/75463370/150276230-65e10091-01a7-4534-9836-0bff7de50cb3.jpg)
![chip info](https://user-images.githubusercontent.com/75463370/150276231-418372f8-7400-4eb2-8448-f9c6f58929dc.jpg)

**Comment by Qrome** [comment]
@jimus888 -- thank you for providing all the details.   From first glance with this type of issue I would say check the ESP8266 core version is 2.5.8 and the 1M SPIFF
![image](https://user-images.githubusercontent.com/32021227/150359293-2e4239d4-2dcc-4184-8908-843c0d5ecab9.png)
It looks like you have covered all that.

What is the LED board you are using?  I wonder if it is a different control chip on the LED board.

**Comment by jimus888** [comment]
Hi. 

Just wanted to let you know I got it working :)

the code was fine. Thanks for your help 

FYI The fix was to power the display from the 3v3 pin on my esp8266 board
