### ISSUE TITLE
Youtube

### ISSUE THREAD

**Issue by locito09** [Qrome/marquee-scroller#235]
you can add Youtube subscription: THX

**Comment by victor7376** [comment]
I've uploaded the code for the YouTube scroller, its the basic coding but does work for informing you of how many subscribers you have, but please read through the readme & YouTube-scroller.ino for the details as there is NO server interface like Qrome's normal scroller.

Its all got to be programmed in before you compile into the D1 Mini.  It uses the same connections to the max7219 displays.

**Comment by Qrome** [comment]
This is great, but there are no plans to integrate YouTube Subscriber count into the main code line.
