### ISSUE TITLE
Problem with blinking seconds

### ISSUE THREAD

**Issue by patolog19694** [Qrome/marquee-scroller#237]
Heloo comunity,im newbie here in this kind of brilliant project so please apologize me if the question would be trivial issue.
I have managed to make scroller work perfectly,except the seconds donť blink.
Is it only my issue and have problem in my setting or is it common issue and the seconds wont blink?
Thanks for any replies and helpful information.
Cheers :)

**Comment by Qrome** [comment]
Couple of questions, what version are you running?   This is not a problem I have ever seen.   Also, the only thing that flashes is the ":" character between the hours and minutes.
Check the box on the configuration page:
![image](https://user-images.githubusercontent.com/32021227/163822360-db5d7792-b51a-40c6-bf5f-e1aa9a0bce5e.png)

**Comment by patolog19694** [comment]
Thank you very much. Everything works as it should. I use version 2.19. My problem is only English.
Thanks again.
