### ISSUE TITLE
keep losing WiFI and ask to reconnect to hotspot

### ISSUE THREAD

**Issue by bertybassett** [Qrome/marquee-scroller#239]
OK so I have a vvvvv strong WiFi from my ubiquiti dream machine router and the D1 mini is less than 2 meters away from said router however my D1 mini keeps losing WiFi and then asking to reconnect to the clock hotspot. Is a setting I can tweak to help prevent this?

BTW I send donation yesterday, its not much but every little helps.

**Comment by Qrome** [comment]
When you view the web interface down at the bottom of the screen does it show the WiFi signal strength as a percentage?   How long is the IP lease from your DHCP server.   I have never experienced what you are describing.   I run the D1 mini all over my house and some even in my back yard and they are always connected.   Check some of your router settings.  Especially on the 2.4Ghz network.    Thanks for the donation!

**Comment by Qrome** [comment]
Try running it a little further from the router.  See if that keeps happening if you give it a little distance.

**Comment by bertybassett** [comment]
DHCP was set to 15 minutes I've changed it to 10 hours let see if that improve it.  

signal on the initial wifi setup page is 92%

**Comment by bertybassett** [comment]
issues on wifi at home end, just don't tell anyone I am a Cisco engineer by trade (where is the embarrassed emoji)
