### ISSUE TITLE
Hour digits are not displayed properly

### ISSUE THREAD

**Issue by PhiB9** [Qrome/marquee-scroller#241]
Hello,
my watch doesn't display the first digits of the time (**HH**:MM) properly. It shows strange symbols instead of the numbers. Every other feature is working well. Anyone having the same problem or a solution? 
I am using a 8*32 LED matrix.
Thanks.

**Comment by Qrome** [comment]
Solution, use the latest 3.0 branch.   This issue crept in with newer versions of the ESP8266 core.   This has been resolved.
https://github.com/Qrome/marquee-scroller/tree/3.0

**Comment by Qrome** [comment]
Also updated the master with the latest.

**Comment by Warent2454** [comment]
> the issue happened when i updated to the 3.0 version. but it was fixed after reset settings

It Only happens when "Use 24 Hour Clock (military time)" is enabled

**Comment by Qrome** [comment]
Yep, I just confirmed that the 24 hour view in version 3.0 has the character issue.   I will have it fixed out later today.  Thanks.

**Comment by Qrome** [comment]
Ok, this is now fixed in 3.01 release.  Let me know if that works for you.   Thanks.

https://github.com/Qrome/marquee-scroller/releases/tag/Scroller_V3.01

**Comment by PhiB9** [comment]
It's working now. Thank you!
