### ISSUE TITLE
(Request) Moonraker Api support

### ISSUE THREAD

**Issue by TimoMF** [Qrome/marquee-scroller#245]
Hello,

I use up to now the Marduee-Scroller with Octoprint.
Because I move, however, my printers bit by bit on clipper, ware it is nicely inserted even if a Moonraker Support.

Greeting Timo

**Comment by victor7376** [comment]
Someone already requested this, I think someone make a fork to support it.

**Comment by TimoMF** [comment]
Unfortunately, for 'marquee-scroller' I can find the inquiry here.
I have not still found a Fork up to now.

I have found with the 'print monitor' only a rowing request.

I have it to me now hingebastelt, but would be better if one of the professionals here does.

Greeting Timo
