### ISSUE TITLE
display the date in the format Day / date of the day / month

### ISSUE THREAD

**Issue by lfugier** [Qrome/marquee-scroller#247]
Hello, By default the date is displayed in the format day/ month / date of the day (example Sunday May 14). 
I would like to display the date in the format Day /date of the day /month (Sunday 14 May). 
How do I modify the code to make this change? 
Thank you for your help.

**Comment by victor7376** [comment]
Look from line 364 and change the lines around where you feel necessary.

**Comment by lfugier** [comment]
Ok thanks, I managed to make the change.
Below is the modification I made to the code (if it can help someone else)


      //if (SHOW_DATE) {                                                                    //
      //  msg += TimeDB.getDayName() + " ";                                  // ==> Date in US format (Monday May 16)
      //  msg += TimeDB.getMonthName() + " " + day() + " ";        // 

     if (SHOW_DATE) {
          msg += TimeDB.getDayName() + " " + day() + " ";  // ==> Date au format Fr (Lundi 16 Mai) [jour/mois dans TimeDB.cpp]
          msg += TimeDB.getMonthName() + " " + " ";
