### ISSUE TITLE
Display not off if started during "Start Time" and "End Time"

### ISSUE THREAD

**Issue by mats-nk** [Qrome/marquee-scroller#256]
I the marquee-scroller is started during the period that the display should be off, configured with **Start Time** and **End Time** the display stays on.

**Comment by Qrome** [comment]
This is true and known.   If you unplug and plug it back in during the defined off period, it will come on.  This behavior assumes you want to see it.   There are no plans to change this.

**Comment by Qrome** [comment]
If you want to shut it off after powering it up, you can do it from the web interface.

**Comment by mats-nk** [comment]
I can correct it, its just **void checkDisplay() {** that has to be tweaked.

**Comment by Qrome** [comment]
Thanks, it can be corrected, however I chose to leave that as an option.   I often will turn mine on after hours by restarting it.

**Comment by mats-nk** [comment]
This will check if the display should be turned off or on regarding to `timeDisplayTurnsOff` and `timeDisplayTurnsOn`.
```
// Toggle on and off the display if user defined times        Mats
void checkDisplay() {
  if (timeDisplayTurnsOn == "" || timeDisplayTurnsOff == "") {
    return; // nothing to do
  }
  String currentTime = TimeDB.zeroPad(hour()) + ":" + TimeDB.zeroPad(minute());

  if (currentTime > timeDisplayTurnsOn && currentTime < timeDisplayTurnsOff) {
    Serial.println("Time to turn display on: " + currentTime);
    flashLED(1, 500);
    enableDisplay(true);
  } else {
    Serial.println("Time to turn display off: " + currentTime);
    flashLED(2, 500);
    enableDisplay(false);
  }
}
```
