### ISSUE TITLE
#define CONFIG "/conf.txt"

### ISSUE THREAD

**Issue by mats-nk** [Qrome/marquee-scroller#258]
Could a template be added to the repository that show how `#define CONFIG "/conf.txt"` should look like.

**Comment by Qrome** [comment]
It is created by the application.  You should be able to pull it off if you want to see it, but the intent is not to create it manually.

**Comment by mats-nk** [comment]
Thx for fast reply, and I thought the intent was to add default values without adding it to the compiled code.

**Comment by Qrome** [comment]
No, the intent is to be a db / file that the application and web interface stores settings.   It is created the first time you run it and is updated and maintained through the web interface.   It does not exist until the first time you run it.   After it is created, you should be able to read and write to it if you want.   The format is name value  pair.

**Comment by mats-nk** [comment]
Thx for the explanation, case closed.
