### ISSUE TITLE
Add Theme Colour Support 

### ISSUE THREAD

**Issue by gmunday2** [Qrome/marquee-scroller#260]
Hi first of all, great project and is it still being worked on?

Also i use your printmonitor as well and thats brilliant and theres theme colour support in it, but not in the marquee scroller, is it possible to add it?

Also on the time on the marquee scroller what  do the little dots under the time represent?

**Comment by Qrome** [comment]
It is being worked as needed.  As for the dots under the time, I am not sure what you mean.   If you are running the printer monitor portion the percentage of the print will grow across the bottom of the clock until it is completed.  There is also a single dot that will show if you are running AM/PM time and is a PM indicator.

**Comment by gmunday2** [comment]
ah ok so it the 3d printer percentage, yep im printing the 3d case you did for it and that makes sense as quite a few dots there now and it is 84% done.

Any chance of adding theme support like your printer monitor one has?

**Comment by gmunday2** [comment]
Also I am making one for my nephew and he loves to send me messages etc..... i was wondering if there could also be support to read text from a custom website page so we could send messages to each other that comes up in the scrolling message?

**Comment by Qrome** [comment]
Added themes.  To answer your question about messages -- this is an open source project -- learn to code and add it.   I have no plans to add that.

You can find the new version 3.02 with theme support here:  https://github.com/Qrome/marquee-scroller/releases/tag/Scroller_V3.02
