### ISSUE TITLE
Weather Data Error: HTTP/1.1 401 Unauthorized

### ISSUE THREAD

**Issue by dirtmover** [Qrome/marquee-scroller#269]
I get this error when I set the OpenWeatherMap API Key from the web interface.
When I hard code it in Settings.h and do a flash reset, everything is fine.

**Comment by finnie2006** [comment]
same

**Comment by Qrome** [comment]
You must activate and verify the key.   This is not a bug.

**Comment by finnie2006** [comment]
It is..

**Comment by Qrome** [comment]
Well, if you are getting a 401 not authorized -- please provide very detailed instructions how this can be replicated.   Nothing here from what I can tell is helpful.

**Comment by dirtmover** [comment]
I told you how in the original issue report but here we go again!.
1. Build a load with _String APIKEY = ""; // Your API Key from http://openweathermap.org/_ in **Settings.h**
2. Reset the flash and install this load on your ESP
3. Configure OpenWeatherMap API Key from the web interface using your **activated and verified key**
4. You'll get "Weather Data Error: HTTP/1.1 401 Unauthorized"
5. Build a new load with your API Key in **Settings.h** i.e. _String APIKEY = "YourApiKey";_
6. Reset the flash and install this load
7. Everything is fine now

**Comment by Qrome** [comment]
Thanks for the details.   I can not replicate it.   I have never had to add the api key to the Settings.h file -- ever.
