### ISSUE TITLE
Timezonedb

### ISSUE THREAD

**Issue by Xcom-Seller** [Qrome/marquee-scroller#271]
Hi Qrome,
Just build a new 20 panel blue scroller. V3.01.
All workf ine apart from I am unable to create a timezonedb API
It states all my email addresses are invalid.
If I got to the contact us and send a message it states "disposable email addresses are not allowed"

**Comment by Qrome** [comment]
Sorry, I don't have control over the API and I have never seen that message before.
Maybe you could reach out to timezonedb.

**Comment by Xcom-Seller** [comment]
I have tried but no joy.
It appears that they have had this problem before, from reading their facebook page.
Hopefully it will be fixed shortly.
Thanks
