### ISSUE TITLE
Foreign languages special characters noy displyed.

### ISSUE THREAD

**Issue by barabasj** [Qrome/marquee-scroller#274]
In my case, News servers return strings including spanish puntuation like accents, letter ñ and others. How I can change the decoding to include those characters?

Thanks!

**Comment by Qrome** [comment]
Those characters are not supported by the fonts in the scroller software. They are purposely removed when they show up.

**Comment by barabasj** [comment]
Hi @Qrome, I've found a conversion routine inside the NewsApiClient.cpp file, but, if this is the way that "special characters" are changed, it is not working for me.
