### ISSUE TITLE
I receive Jan 1 12:00 e every time I reset. 

### ISSUE THREAD

**Issue by BruteSource** [Qrome/marquee-scroller#280]
The news works and the temps seem correct for Phoenix where I live. But the time and date are always Jan 1 12:00 when I reset. The news works.. I have double checked my two APIs are correct and that my city code is right. 
I am using the latest version but it was doing the same thing with previous version. Any suggestions  please?

**Comment by Qrome** [comment]
Make sure you have activated the timedb API.   This is the typical mistake.

**Comment by BruteSource** [comment]
Again all the APIs function correctly with manual URL requests. I have signed in to verify the API and created a new one.

**Comment by Qrome** [comment]
Then run the port monitor in the IDE on baud rate 115200 -- you will see the error.   I have seen this before.
