### ISSUE TITLE
Weather Error: Weather Data Error:

### ISSUE THREAD

**Issue by editwentyone** [Qrome/marquee-scroller#283]
hi, I'm on 3.0.3 and compiled myself but also updated afterwards through UI. reseted flash before and after, nothing helps.

all I get is the "Weather Error: Weather Data Error:" error. its even a fresh API key, but still, no changes, since hours. any ideas?

![Bildschirmfoto 2023-11-28 um 22 15 35](https://github.com/Qrome/marquee-scroller/assets/96262473/705f5743-2ee7-478b-ab9a-31258abe5407)

**Comment by Qrome** [comment]
Connect to the Arduino IDE and use the port monitor to view the error.   It should tell you what is happening.   Baud 115200.

**Comment by editwentyone** [comment]
```
10:46:00.620 -> 
10:46:00.620 -> Getting Weather Data
10:46:00.620 -> GET /data/2.5/group?id=MYCITY&units=metric&cnt=1&APPID=MYAPI HTTP/1.1
10:47:00.707 -> Waiting for data
10:47:05.703 -> Response Header: 
10:47:05.703 -> Unexpected response: 
10:47:09.867 -> Updating Time...
10:47:09.867 -> essful!
10:47:09.867 -> Getting Time Data for ,
10:47:09.867 -> GET /v2.1/get-time-zone?key=MYAPI&format=json&by=position&lat=&lng= HTTP/1.1
10:47:25.063 -> Waiting for data
10:47:25.063 -> 
10:47:25.063 -> 
10:47:25.063 -> firstEpoch is: 20
10:47:25.063 -> Getting News Data for reuters
10:47:25.063 -> Please provide an API key for the News.
10:47:25.063 -> Version: 3.03
10:47:25.063 -> 
11:02:25.124 -> 
11:02:25.124 -> Getting Weather Data
11:02:25.124 -> GET /data/2.5/group?id=MYCITY&units=metric&cnt=1&APPID=MYAPI HTTP/1.1
11:03:25.109 -> Waiting for data
11:03:30.104 -> Response Header: 
11:03:30.104 -> Unexpected response: 
11:03:34.266 -> Updating Time...
11:03:34.266 -> essful!
11:03:34.266 -> Getting Time Data for ,
11:03:34.266 -> GET /v2.1/get-time-zone?key= MYAPI&format=json&by=position&lat=&lng= HTTP/1.1
11:03:49.359 -> Waiting for data
11:03:49.359 -> 
11:03:49.359 -> 
11:03:49.359 -> Time update unsuccessful!
11:03:49.359 -> Getting News Data for reuters

```

**Comment by Qrome** [comment]
Honestly, it looks like a connectivity issue. My guess is that it timed out waiting 1 minute from making the request. Make sure that on the network that your device is on it can actually reach full URL and is not being blocking the weather service. I have seen this before.

**Comment by editwentyone** [comment]
what is the URL to test that in a browser on a desktop machine?

**Comment by editwentyone** [comment]
tested this on my desktop: https://api.openweathermap.org/data/2.5/group?id=MYCITY&units=metric&cnt=1&APPID=MYAPI

and got an answer inside a browser, so it shouldn't be the pihole on my network (checked the logs there too)

**Comment by editwentyone** [comment]
same goes for http://api.timezonedb.com/v2.1/get-time-zone?key=MYCITY&format=json&by=position&lat=MYLAT&lng=MYLONG its working fine in my browser

**Comment by Qrome** [comment]
I know you are testing on your browser, however the device runs in the 2.4Ghz network and make sure that your browser / computer is on the exact same IP range and subnet as the scrolling clock device.   Again, this isn't a coding issue, but probably a network issue, and I have seen this before where the different networks have blocking lists etc.

**Comment by Qrome** [comment]
> 10:46:00.620 -> GET /data/2.5/group?id=MYCITY&units=metric&cnt=1&APPID=MYAPI HTTP/1.1
10:47:00.707 -> Waiting for data
10:47:05.703 -> Response Header: 

This is what tells me you are being blocked.   Timed out and no response -- there is a 60 second delay there.

**Comment by editwentyone** [comment]
will test with different wifi (not guest anymore), will report back

**Comment by editwentyone** [comment]
ok @Qrome, reflashed and brought to the main network (no guest network anymore) and bam, its working. shame on me. 
but something is blocking and you were right. thanks for your time

**Comment by Qrome** [comment]
Hey, thanks for the update.   I hope this can help others.
