### ISSUE TITLE
Issue with time

### ISSUE THREAD

**Issue by MrJabu** [Qrome/marquee-scroller#30]
I used the OpenWeather site to find my 7 digit city ID. It works in the marquee to pull the weather but the time is off by 4hrs.

**Comment by Qrome** [comment]
You need to create and activate an account with GeoNames that is where it gets the time offset.   This is not a bug.

**Comment by Qrome** [comment]
This is the line in the README.md file:

`GeoNames Key (optional as you can use mine or create your own) http://www.geonames.org/ -- this key is only managed in the Settings.h file.`

**Comment by MrJabu** [comment]
i did do that and entered my username in setting.h but it didn't change

**Comment by Qrome** [comment]
Please test your GeoNames account with this URL:

http://api.geonames.org/postalCodeCountryInfo?username=[USERKEY]

Replace [USERKEY] with your valid key.   If it gives you full set of data then it should work.   I have a feeling you do not have your account setup correctly.

**Comment by MrJabu** [comment]
BINGO...i am an idiot.

Thanks for helping! Awesome project.

Closed!
