### ISSUE TITLE
Display doesn't work

### ISSUE THREAD

**Issue by SkromnyNick** [Qrome/marquee-scroller#32]
Hi!
My clock doesn't work. The whole or half screen is all time on. Sometimes it blinks.
D1 Mini and screen work because everything is good using a different script (https://drive.google.com/file/d/1cBPUl9tztSOoEt1IL99C2vWOICdgKlcq/view)
Can you help me?

![img_20180720_191234](https://user-images.githubusercontent.com/41485823/43016349-cf3457ae-8c52-11e8-8db1-d8c3d1b650cf.jpg)

**Comment by Qrome** [comment]
The code you tested with is using totally different pins.  

`// MAX 7219 WEMOS
const byte CS = 0;    // D3
const byte CLK = 4;   // D2
const byte DIN = 2;   // D4`

YOU MUST use the pins in the documentation for the code or change the code to use the same pins you have wired up right now.   Does that make sense?

![Marquee Scroller Wiring](/images/marquee_scroller_pins.png)

**Comment by Qrome** [comment]
Not sure what to say.  The only time I have seen that behavior is when it isn't wired up correctly.  Can you give some details about the hardware you are using?   Is it a Wemos D1 Mini?

**Comment by SkromnyNick** [comment]
[https://www.aliexpress.com/item/ESP8266-ESP-12-ESP-12F-CH340G-CH340-V2-USB-WeMos-D1-Mini-WIFI-Development-Board-D1/32674463823.html?spm=a2g0s.9042311.0.0.27424c4daHW0i4](url)
and
[https://www.aliexpress.com/item/MAX7219-Dot-Matrix-Module-For-Arduino-Microcontroller-4-In-One-Display-with-5P-Line/32637207300.html?spm=a2g0s.9042311.0.0.27424c4daHW0i4](url)

**Comment by SkromnyNick** [comment]
Thanks for the help....

**Comment by SkromnyNick** [comment]
U can't help me so you closed the topic?
