### ISSUE TITLE
I'm having an issue with the Web interface. 

### ISSUE THREAD

**Issue by DNAJAY** [Qrome/marquee-scroller#35]
Hello! Awesome Clock. Small issue. I've connected everything, and got the "hello" screen. Then it gives me the IP address, which does not appear to be valid. Then marquee sits with one dot indefinitely. I assume it's because I haven't gotten into the web interface yet. 

Also, is there a way to reset the board to pick a new internet connection? I tried simply reuploading the code, but it keeps the same IP, and is no longer a hotspot. Any thoughts? Thanks!

**Comment by DNAJAY** [comment]
Actually I figured it all out! Turns out to reset the board you just need to select "tools" then erase flash, and make sure to reset the wifi settings too.  Once I did that, and connected to a better wifi, all was good. Thanks for making this awesome thing!

**Comment by Qrome** [comment]
Glad you were able to get it all sorted out.
