### ISSUE TITLE
Link to the Ota updater

### ISSUE THREAD

**Issue by hutje** [Qrome/marquee-scroller#38]
Normally the link to the update page is: xxx.xxx.xxx.xxx/update but this is redirected to homepage.
How can I wirelessly update?

**Comment by hutje** [comment]
Okay, just inside the Arduino IDE?

**Comment by Qrome** [comment]
Yeah, you have to compile the code first anyway to get the hex binary.   You can read about it here under the Classic OTA section:  http://esp8266.github.io/Arduino/versions/2.0.0/doc/ota_updates/ota_updates.html

**Comment by satbeppo** [comment]
And don't forget to turn off your FW before Update OTA !

**Comment by magnum129** [comment]
I just added this via a PR. It looks like it'll be added in 2.5.

**Comment by Qrome** [comment]
Binary files can now be loaded through the web interface under "Update Firmware"
