### ISSUE TITLE
Clock displays UTC until first refresh of data

### ISSUE THREAD

**Issue by westerncanada** [Qrome/marquee-scroller#41]
The clock displays time in UTC until the weather data is refreshed the first time, vs the first time it loads.

As a work around I've added at line 291
``handlePull();
``
which works, but is a bit of a hack.

**Comment by Qrome** [comment]
What version are you using?   I am not able to replicate this.   The weather data pull is required and is the 1st thing it does.  It uses the Latitude and Longitude to make a call and get the timezone offset.   

I am not able to replicate this.  Can you share more about your setup?   
Version?

**Comment by Qrome** [comment]
If your first weather call is failing then this could cause this issue.  If the GeoNames service is failing on the first call then you could get the UTC time.   I am not able to replicate this.

**Comment by westerncanada** [comment]
I'm using version 2.2.

My Location is Edmonton, Alberta, Canada - and there is more than one "Edmonton" returned when searching manually.  but I'm using ID: 5946768

I wonder if it's not failing the first call... I'll do a bit of debugging to see what is going on.

Thanks for a cool clock

**Comment by Qrome** [comment]
I just tested my clock with your city ID -- no issues.

Try running with the serial monitor on.   See if it is the Weather call or the GeoNames call that is failing.   The Serial Monitor should be able to show you the stack of service calls when it is booting up.

By the way, I was just up in Alberta a few weeks ago.  Lethbridge and Waterton area.   Really nice area up there.   I have not made it up to Edmonton yet, but sometime we will probably make it up there.

Let me know what you find out.

**Comment by westerncanada** [comment]
I copied the output of the serial monitor from boot up, and then after I do a /pull which starts on line 100.

The output is sanitized for API keys, passwords and the username for the geolocation, the news headlines are snipped for brevity.

Note that the boot up time is showing UTC, and right after the pull it shows the DST adjusted time.

Gist of the outputs available [here](https://gist.github.com/westerncanada/72a15d3b3928bb1fb3b60e42940d7dd7)

I don't see it failing the lookups, all I see different is the "firstEpoch is:" line.

Thanks for looking into it.

Well, a belated welcome to our fair province to you.  I love it here, you can start your day in the city, then drive an hour or two and be in the bush, near the mountains.  If you get a chance Jasper and Banff are beautiful as well.

**Comment by DynaMight1124** [comment]
Actually mine does this too, when I first plug it in I get 1 hour earlier, but after the first refresh, it amends to the latest time. I'm in the UK so it goes from GMT to BST. It did the same in 2.1 and also 2.2.

**Comment by Qrome** [comment]
I have not experienced this issue.  Very odd.  My timezone does not have a Daylight Savings offset either.  Anyway, I have made some changes that can be found in the 2.3 dev branch.  I have tested using the Edmonton city ID and it appears to display the correct time every time.  If you guys could pull it down and give it a try, that would be great.

https://github.com/Qrome/marquee-scroller/tree/2.3

Thanks.

**Comment by westerncanada** [comment]
I've pulled version 2.3 down to try, and it seems to have fixed the issue.   Thanks!

**Comment by DynaMight1124** [comment]
Yeah just tried 2.3 and it's working fine now. Thanks.

**Comment by Qrome** [comment]
Thanks guys, this will be part of the official 2.3 release.

**Comment by Qrome** [comment]
Included in 2.3 release.
