### ISSUE TITLE
Day of the month

### ISSUE THREAD

**Issue by eduardoborgess** [Qrome/marquee-scroller#48]
In the last version (2.3) the day of the month is not updated.
This number is correct only on the start-up day. I wonder if anyone else has the same problem.

Thanks, Eduardo

**Comment by Qrome** [comment]
Mine updates.   It should update at midnight.

**Comment by eduardoborgess** [comment]
On start-up day the number of the day is always correct. if the system stays on for several days, it will always continue to display the day of the month it took over the boot. In other words: although there have been several changes in the day, the number remains unchanged.

**Comment by Qrome** [comment]
On line number 309 of the marquee.ino file is where it reaches out to GeoNames to update at 00 hour 00 min and 00 seconds.   This is working on all my clocks and they are showing the correct date this morning.

What is your scroll frequency set to?  How often do you have the scroll set?   I am wondering if it isn't falling into that code for you at midnight.

**Comment by Qrome** [comment]
The day of the month there comes from the GeoNames service.   If that service isn't pulling correctly for you then the day of the month will not be correct.   Can you verify your GeoNames service.   Again, this is working on all my clocks and others.

`String time = geoNames.getMonthName() + " " + geoNames.getDay(false) + ", " + timeClient.getAmPmFormattedTime();`

This is the line in the file that builds the HTML display for the time and date on line 982 of the marquee.ino file.

**Comment by eduardoborgess** [comment]
Hello.
I also have three devices and they all have the same error.

 It does not seem to be a GeoNames problem because either on the day of the startup or when the day of the month is already late, doing Refresch the day is correct.

 If there was an anomaly of GeoNames in these situations I described the day would be wrong ....

**Comment by eduardoborgess** [comment]
Hello everyone.

At last I I understood why the number of the day does not automatically update the next day.

Set the time to turn the ledmatrix off between 00:00 and xx: xx.

In this case when the shutdown period starts at 00:00 the number of the day does not change.

If the start time is different from 00:00 then the day number changes automatically.

Probably has to be with the coincidence of 00:00 - change of day.

I leave here the conditions in which the error manifests itself. Certainly the author will make his correction.

Good job.

**Comment by soluna1** [comment]
Hi everyone, 
Similar issue, day is correctly displayed but not date (number of day and month). In the Open weather website  it is correct, but not in the web environment of the clock, eg. monday, 0. 
any idea?

thanks

**Comment by Qrome** [comment]
Do you have it set to turn off at midnight?   If so, move it one minute before or after.

**Comment by dagopeter** [comment]
Hi Qrome - I have an other issue . After the start there is always the same date, time and year 1 January 1970. thursday 
![marquee_bild_ohne_Jahr](https://user-images.githubusercontent.com/51929544/59632830-6d124780-914b-11e9-814b-e0743ca8a902.jpg)

There is no change at all I have ever tried. Perhaps you know, what it is. Thank you in advance. Peter

**Comment by dagopeter** [comment]
..... I forgot to mention - all other features seem to work at all. Changing cities a.s.o.....

**Comment by Qrome** [comment]
@dagopeter -- I see from your screenshot you are running the latest version.   The last few versions require an API key for the timezone service.   Click on configure and follow the prompts.

**Comment by Qrome** [comment]
@dagopeter -- closing this is an old issue and has been resolved.
