### ISSUE TITLE
Enhancement; Add Feature to display Pihole Stats.

### ISSUE THREAD

**Issue by psu1989** [Qrome/marquee-scroller#49]
I think this would be a good feature.  Thanks!

**Comment by Qrome** [comment]
@psu1989 -- just an update.  I release a separate project recently called Pi-hole Monitor -- it can be found here:  https://github.com/Qrome/Pi-hole-Monitor

I wrote the api class file that I plan on implementing the option for basic stats in the Marquee Scroller.

**Comment by Qrome** [comment]
Pi-hole statistics coming very soon.   This will also display with the wider displays.
![pi-hole-graph](https://user-images.githubusercontent.com/32021227/56696946-3ca9b200-66a2-11e9-86ef-e406d9441092.jpg)

**Comment by Qrome** [comment]
Released in v2.12
