### ISSUE TITLE
Please add Week Day Display.

### ISSUE THREAD

**Issue by Neeraj-Ch** [Qrome/marquee-scroller#50]
_Thanks_ **Qrome**_, for this awesome idea. I made one for my Home Usages.
I have some issues or say Enhancement required._

1. Add week days display while scrolling. i.e. Sunday, Monday.
2. Add AM or PM/small symbol representation with Time.
3. News/Weather Info. Updating in backgroung while time still showing. i.e you can add a progress bar on 
 Main Screen
4. If possible please Automate brightness of display using LDR/light sensor. or Lower the brightness of Display further

**Please Please Please...**

**Comment by Neeraj-Ch** [comment]
Hello _Qrome._
still waiting for updates...

**Comment by Qrome** [comment]
Day of the week was included in 2.4 last week.   Thanks.
