### ISSUE TITLE
Add MQTT-to-text display?

### ISSUE THREAD

**Issue by yang3535** [Qrome/marquee-scroller#58]
This is a great little clock.

A enhancement request - it would be really nice to use MQTT to publish the text to be displayed as "advice" so that home automation systems, or other computers can send text messages to be displayed.

**Comment by yang3535** [comment]
moving to existing thread - closing as a separate issue

**Comment by Qrome** [comment]
Thanks for managing the thread.    as for MQTT -- I don't have any devices currently to even test this.  If someone would like to contribute a solution in the code, we could have people test it out.
