### ISSUE TITLE
DST/GMT

### ISSUE THREAD

**Issue by davericher** [Qrome/marquee-scroller#59]
This change actually has the reverse effect here in EST
https://github.com/Qrome/marquee-scroller/blob/55f661b195c6692f39030ecae9c1fb4dd8b45ec6/marquee/GeoNamesClient.cpp#L85

**Comment by Qrome** [comment]
East coast is currently off Daylight Savings Time as of Nov 4th.   If you are running the latest code, you can un-check the option to use DST.   This would give you the GMT - 5 for EST.     The change in the code didn't give the reverse affect here.   The code previously was always giving DST.  Now you can select DST or not.

**Comment by johnpitcavage** [comment]
I am having the same DST problem. I have DST set to false and I am still getting the DST offset from GMT.

**Comment by Qrome** [comment]
Is the DST option still showing in the web interface?  You need to manage the setting through the web interface.

**Comment by johnpitcavage** [comment]
I get the DST option on the web interface but it does not appear to change the offset.  I also get a questionable response from Geonames on the console for my EST  : 
"sunrise":"2018-11-19 06:54","lng":-78.64,"countryCode":"US","gmtOffset":-5,"rawOffset":-5,"sunset":"2018-11-19 17:05","timezoneId":"America/New_York","dstOffset":-4,"countryName":"United States","time":"2018-11-19 09:24","lat":35.77}
rawOffset for America/New_York is: -4"

The rawOffset for  America/New_York is wrong.  I will keep looking.  

Thanks,  Great project!

**Comment by Qrome** [comment]
If you uncheck the DST option, then the code should use the gmtOffset of -5  and this is correct for New York.

**Comment by johnpitcavage** [comment]
You are right on the offset, it should be -5 for standard time.  The problem is I am getting -4.  I am wondering why I get "rawOffset for America/New_York is: -4".  I'll keep after it, it might be something with the Json Parser.  I did compare you github files with my Arduino but I couldn't identify any changes I might have made.  I might need to update the ArduinoJson, I was betting a compiler error with the latest.  I am using 5.13.2.

**Comment by johnpitcavage** [comment]
My problem was "operator error.  I failed to scroll down on the config page and hit the save button so my DST change was not executed.

Thanks for you help!

**Comment by Qrome** [comment]
John, glad you got it all working.  Also, thanks for the donation!  It is much appreciated!
