### ISSUE TITLE
Matrix panel order

### ISSUE THREAD

**Issue by JPGTJ71** [Qrome/marquee-scroller#65]
Hi. Is there a way to change the panel order? In my build everything compiles but I get the panel order mixed up.  Here's a pic to explain better. Should say "hello" 
![hello](https://user-images.githubusercontent.com/45112634/48654945-30416f00-ea09-11e8-8700-150d97c5bccf.jpg)
It's like instead of order 1234, I get 4321
Thanks in advanced

**Comment by JPGTJ71** [comment]
Thanks! 
Worked by matrix.setRotation (i, 1)

**Comment by Qrome** [comment]
Hey, that is great.  Cool.
