### ISSUE TITLE
Not updating for daylight savings

### ISSUE THREAD

**Issue by MrJabu** [Qrome/marquee-scroller#66]
Hello,

i have noticed that the clock has not corrected -1hr for daylight savings. how can i adjust this?

thanks

**Comment by Qrome** [comment]
Yes, it has been noticed.  Download and install the latest version of the firmware.  You will then see a check box on the confirmation page to turn on or off the DST.

**Comment by anthonyjclarke** [comment]
Just made a donation... love it....
Same thing for me, thanks this fixes the DST issue...
Wondering how possible it would be to integrate this library to automate this?
https://github.com/neptune2/simpleDSTadjust
