### ISSUE TITLE
Display time to turn on/off not working

### ISSUE THREAD

**Issue by MrJabu** [Qrome/marquee-scroller#67]
i have the time to turn on set to 8:00 AM and turn off at 10:00 PM. For some reason with the latest update the screen stays on past 10:00 PM.

Any thing i can try?

**Comment by Qrome** [comment]
10:00 PM should be 22:00  -- what time did you put in there? 

This works for me as I use 11:00 PM -- so I have 23:00.   Make sure you are updating it using the web interface.   Once the firmware is loaded you can't make changes from the Setting.h file unless you erase all the memory.

**Comment by MrJabu** [comment]
i set it through the web interface to 10:00 PM

**Comment by MrJabu** [comment]
![time](https://user-images.githubusercontent.com/21026988/48820325-7b69c380-ed22-11e8-973a-71777c9f8ae9.png)

**Comment by MrJabu** [comment]
right now its 12:15 AM

**Comment by MrJabu** [comment]
ooooh. that did it. i did unplug it. good to know. Thanks!

**Comment by Qrome** [comment]
Cool, glad that solved it.   If it is glowing and keeping you up, you can turn off the screen from the menu -- it will turn back on when it hits your 8:00AM time on.   Cheers!
