### ISSUE TITLE
Port the wemos board to wemos D1 Mini pro

### ISSUE THREAD

**Issue by Neeraj-Ch** [Qrome/marquee-scroller#69]
Hello Qrome.
Everything just awesome. 
Thanks for such a great work.

I have a request if you can port the whole thing to Wemos D1 Mini Pro module.
As you know it has more memory i.e. 16 MB. & Good wifi reception.

So that we can use a much complex tasks & programming on our Marquee- Scroller.
Please have a look at this board.

**Comment by Qrome** [comment]
Does it not work with the Mini Pro board now?  I have not tried but I know people also run it with the ESP32 boards.

**Comment by Neeraj-Ch** [comment]
Yes, it works well on Esp 32. But we can develop a more complex machine. Please think about more modifications.
Thanks
