### ISSUE TITLE
Problem with UTC

### ISSUE THREAD

**Issue by sorriso93** [Qrome/marquee-scroller#71]
Hello
I verified a problem with UTCoffset but I cannot understand where the fix has to be made...

in this code, seeing on serial output, time is ok (1) (geonames client cpp)

datetime = (const char*)root["time"];
  Serial.println("rawOffset for " + String((const char*)root["timezoneId"]) + " is: " + offset);
  Serial.println("Geo Date & Time: " + getMonthName() + " " + getDay(false) + ", " + getHours() + ":" + getMinutes());
  Serial.println();

but then when it is visualized in the matrix with this code I get the time + 1 hour....(2) (loop in the main code)

String hourMinutes = timeClient.getAmPmHours() + ":" + timeClient.getMinutes();
  if (IS_24HOUR) {
    hourMinutes = timeClient.getHours() + ":" + timeClient.getMinutes();
  }
  if (numberOfHorizontalDisplays >= 8) {
    if (Wide_Clock_Style == "1") {
      // On Wide Display -- show the current temperature as well
      hourMinutes = geoNames.getMonthName() + " " + geoNames.getDay(false) + " - " + timeClient.getHours() + ":" + timeClient.getMinutes();
      String currentTemp = weatherClient.getTempRounded(0);
      String timeSpacer = "  ";
      if (currentTemp.length() >= 3) {
        timeSpacer = " ";
      }
      hourMinutes += timeSpacer + currentTemp + getTempSymbol();
    }
    if (Wide_Clock_Style == "2") {
      hourMinutes += ":" + timeClient.getSeconds();
      matrix.fillScreen(LOW); // show black
    }
    if (Wide_Clock_Style == "3") {
      // No change this is normal clock display
    }
  }
  centerPrint(hourMinutes);

I tried to change offset variable to -1 but it is not the solution, it changes the time only on (1)... not in the matrix...

**Comment by Qrome** [comment]
Sorry, please first state what you think the issue is.  What is happening and any details like what version of the code you are looking at.

The DST item has already been addressed.  You can turn on or of DST to adjust your time in the Web Interface in the latest release.

**Comment by sorriso93** [comment]
Correct! I was using 2.3, will try the last. Many thanks

**Comment by Qrome** [comment]
Cool, glad you got that sorted.   I just release version 2.6 -- it also contains the pre-compiled binary files for updating over the web interface.
