### ISSUE TITLE
Version 2.6 causes all or most of matrix illuminated and hangs

### ISSUE THREAD

**Issue by dino340** [Qrome/marquee-scroller#73]
Updated existing hardware (worked fine on 2.4) and flashed new hardware (Wavgat D1 Mini), Both clocks either display all LEDs lit or most lit (nonuniform unchanging unlit pixels). Cannot seem to find either clock or connect via wifi.

Flashed with Arduino IDE 1.8.8
LOLIN(WEMOS) D1 R2 & mini, 80MHz CPU speed, Flash size 4M (no SPIFFS) v2 lower memory, All Flash Contents (after trying other options)

**Comment by Qrome** [comment]
Honestly, it sounds like you have hardware issues.   there is nothing in the code that changed the control of the LEDs -- check the pins on your LED strips that they are all connected.   

Try loading the clock from the compiled binary included in the 2.6 released.

I am using Arduino 1.8.5 with ESP8266 core 2.4.2 -- there have been  no changes in the LED operation.  In fact the memory usage is lower in 2.6 as it no longer includes Advice Slip.   I am wondering if you have issues with a newer library or something around Arduino 1.8.8.

Also, why does your say (no SPIFFS)?

**Comment by Qrome** [comment]
I just tested with Arduino 1.8.8 -- mine defualted to (1M SPIFFS) and worked just fine.  So it isn't 1.8.8 -- I have a feeling you loaded the new beta version of ESP8266 Core of 2.5.X -- even with that the version 2.6 should work as that has been tested as well.

I am sure it is related to the (no SPIFFS) -- SPIFFS is required for the settings file to save and load settings.  this would cause it to hang on boot.  The odd thing is, I don't even have the option to select (no SPIFFS).

**Comment by Qrome** [comment]
Ok, I have now loaded the newer Beta ESP8266 core 2.5.0 and it did default my settings to (no SPIFFS) in Arduino 1.8.8.   I selected (1M SPIFFS) and loaded it and it is working just fine.   I suspect that was your issue since it was hanging trying to load the settings on boot.   Please confirm and I will close the issue.

**Comment by dino340** [comment]
My original clock is indeed working fine after selecting 1M SPIFFS, the issues with the 2nd board were caused by me reversing the wires to pins 5 and 7 and after rectifying that it is also working as well.

Thank you Qrome for your patience, the Arduino IDE constantly telling me to update libraries to beta versions seems to have caused me no end of issues with your clock code, as a suggestion could you please list which versions of the libraries to use? Though that will be less of an issue now that I can upload binaries through the web interface.

**Comment by dino340** [comment]
One other small tangential issue, your released code is configured for 8x1 matrixes instead of the default 4x1, caused a little bit of confusion until I realized this and rectified it.
