### ISSUE TITLE
How to change the NTP server

### ISSUE THREAD

**Issue by hznupeter** [Qrome/marquee-scroller#76]
i cant use google in China ,so , how to change the NTP server ?

**Comment by Qrome** [comment]
Edit the TimeClient.h file on line 42.

`    const char* ntpServerName = "time.google.com";`

Change that to what ever you want to use.   Good luck.

**Comment by hznupeter** [comment]
i've changed ,but it cant work.
do i need modify in the TimeClient.cpp file on line 44:
``` String("Host: www.google.com\r\n") +```

and the Serial.print cant output the infomation no matter what speed i set

**Comment by Qrome** [comment]
Make sure SPIFFS is set to 1MB when compiling.
