### ISSUE TITLE
Daylight Savings in Australia / Automated using Neptunes library

### ISSUE THREAD

**Issue by anthonyjclarke** [Qrome/marquee-scroller#79]
Just made a donation... love it....
Wondering how possible it would be to integrate this library to automate this?
https://github.com/neptune2/simpleDSTadjust

**Comment by magnum129** [comment]
This can probably be closed since the time library has been updated to a source that handles DST automatically.

**Comment by Qrome** [comment]
Closing... this was addressed in 2.10 release.   Thanks.
