### ISSUE TITLE
LED Panels displaying incorrectly

### ISSUE THREAD

**Issue by cknieriem** [Qrome/marquee-scroller#84]
I purchased what I thought were 2 batches with the same SKU LED panels from Banggood.  One set works fine but the other batch initially displays "hello" backwards and misformed.  The items are 

Geekcreit® MAX7219 Dot Matrix Module 4-in-1 Display For Arduino

Any ideas.  Maybe a different driver?
--

**Comment by sorriso93** [comment]
I had the same problem. Try to modify setrotation for the panel inverted. For example I have a mixed configuration: first three panels with rotation 1 and 1 panel with rotation 3...

**Comment by Qrome** [comment]
There are other brands than the one linked to in the readme file, however they work.   Some are assembled differently with different orientations.   You can adjust the orientation easy in the new 2.7 release branch.

https://github.com/Qrome/marquee-scroller/tree/2.7

Look for ledRotation in the Settings.h

**Comment by cknieriem** [comment]
Thank you.  Rotation back to zero fixed the problem with this batch of panels.

**Comment by Qrome** [comment]
Very cool.

**Comment by Qrome** [comment]
The latest version release allows you to change orientation in the Settings.h file.   Thanks. guys.
