### ISSUE TITLE
Login and password issue

### ISSUE THREAD

**Issue by phgsbr** [Qrome/marquee-scroller#89]
Hello, thanks for the clock!

I configuring mine and I'm having an issue. I tried to change the default password and and now no one login is accepted. I tried to download the sketch and compile again with the stock login infos. I tried to unable the login. No success. What can i do?

**Comment by Qrome** [comment]
Plug it in to your computer and run the serial monitor -- it will show you the password when it boots up in the output.  

I have noticed this issue when Chrome is inserting (pre-populating) fields.

**Comment by phgsbr** [comment]
Problem solved. Thank you.
