### ISSUE TITLE
Not able to connect to open wifi network

### ISSUE THREAD

**Issue by Elessar-lad** [Qrome/marquee-scroller#93]
Hi,

Thank you for this amazing project! just fantastic. 

I tried today unsuccessfully to connect to an open WiFi network. I can see it on the WiFi manager, select it and leave the password blank, save the changes, but the wemos never connects. I'm running FW 2.8

Is there something that I need to do?

Thanks again.

**Comment by Qrome** [comment]
I connect to an open network at my office without a password, so I know that works.   Is it possible that the network you are trying to use is rejecting it?

**Comment by Elessar-lad** [comment]
Let me try that right now. I'll create an AP with my phone.

**Comment by Qrome** [comment]
If it is one of those open networks that takes to you an agreement page before allowing you to use the network -- that could be a problem.   You may want to check over at the WifiManager lib page and see if there are some options.

**Comment by Elessar-lad** [comment]
I think that's actually the problem. I was able to connect with my phone with no issue. That WiFi network AFAIK shouldn't ask for that, but I'll double check for sure.

Thanks a lot for your support and terrific work! You may close this 👍
